Repository HDFGroup/hdf4, pull requests merged in 2023-05, with the labels that each got.

#348 Clean up warnings in hdf/test/macros
  hdf/src/hdfi.h
  hdf/test/macros.c
Labels: Component - Testing, Type - Improvement, Priority - 3. Low 🔽

#349 Clean up hrepacktst.c
  mfhdf/hrepack/hrepacktst.c
Labels: Component - Tools, Component - Testing, Type - Improvement, Priority - 3. Low 🔽

#347 Remove the XDRSTDIO ifdefs
  mfhdf/libsrc/putget.c
  mfhdf/libsrc/xdrstdio.c
Labels: Component - C Library, Type - Deprecation / Removal, Priority - 3. Low 🔽

#353 Fixes warnings in src/hblocks.c and test/blocks.c
  hdf/src/hblocks.c
  hdf/test/blocks.c
Labels: Component - C Library, Component - Testing, Type - Improvement, Priority - 3. Low 🔽

#356 Fix GH #355 mismatched macros
  java/src/jni/hdfsdsImp.c
  release_notes/RELEASE.txt
Labels: Component - Java, Type - Bug, Priority - 0. Blocker ⛔

#357 Add cmake presets and workflow
  .github/workflows/clang-format-check.yml
  .github/workflows/clang-format-fix.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/daily-build.yml
  .github/workflows/tarball.yml
  .gitignore
  CMakeInstallation.cmake
  CMakePresets.json
  config/cmake-presets/hidden-presets.json
  config/cmake/examples/CTestScript.cmake
  config/cmake/examples/HDF4_Examples.cmake.in
  config/cmake/examples/HDF4_Examples_options.cmake
  release_notes/INSTALL_CMake.txt
  release_notes/RELEASE.txt
Labels: Component - Build, Component - Testing, Type - Improvement, Priority - 1. High 🔼
