Repository HDFGroup/hdf4, pull requests merged in 2023-09, with the labels that each got.

#428 Rework private header content
  bin/h4_release_check.sh
  hdf/src/CMakeLists.txt
  hdf/src/Makefile.am
  hdf/src/atom.c
  hdf/src/atom.h
  hdf/src/bitvect.c
  hdf/src/bitvect.h
  hdf/src/cdeflate.c
  hdf/src/cdeflate.h
  hdf/src/cnbit.c
  hdf/src/cnbit.h
  hdf/src/cnone.c
  hdf/src/cnone.h
  hdf/src/crle.c
  hdf/src/crle.h
  hdf/src/cskphuff.c
  hdf/src/cskphuff.h
  hdf/src/cszip.c
  hdf/src/cszip.h
  hdf/src/df.h
  hdf/src/dfstubs.c
  hdf/src/dfstubs.h
  hdf/src/dynarray.c
  hdf/src/dynarray.h
  hdf/src/hbitio.c
  hdf/src/hbitio.h
  hdf/src/hchunks.c
  hdf/src/hchunks.h
  hdf/src/hcomp.c
  hdf/src/hcomp.h
  hdf/src/hdatainfo.c
  hdf/src/herr.c
  hdf/src/herr.h
  hdf/src/hfile.c
  hdf/src/hfile.h
  hdf/src/linklist.c
  hdf/src/linklist.h
  hdf/src/mfan.c
  hdf/src/mfan.h
  hdf/src/mfanf.c
  hdf/src/mfani.h
  hdf/src/mfgr.c
  hdf/src/mfgr.h
  hdf/src/mfgri.h
  hdf/src/mstdio.c
  hdf/src/mstdio.h
  hdf/src/src.inc
  hdf/test/mgr.c
  hdf/test/tdatainfo.c
Labels: Component - Build, Component - C Library, Component - Fortran, Component - Tools, Component - Testing, Type - Improvement, Priority - 3. Low 🔽

#429 Remove dead code from tbbt
  hdf/src/tbbt.c
  hdf/src/tbbt.h
Labels: Component - C Library, Type - Improvement, Priority - 3. Low 🔽

#430 Puts herr macros in do..while loops
  .clang-format
  hdf/src/cdeflate.c
  hdf/src/crle.c
  hdf/src/cskphuff.c
  hdf/src/cszip.c
  hdf/src/dfcomp.c
  hdf/src/dfconv.c
  hdf/src/dfgroup.c
  hdf/src/hbitio.c
  hdf/src/hcomp.c
  hdf/src/herr.h
  hdf/src/hkit.c
  hdf/src/vconv.c
  hdf/src/vgf.c
  hdf/src/vsfld.c
  mfhdf/libsrc/mfdatainfo.c
  mfhdf/libsrc/mfsd.c
Labels: Component - C Library, Type - Improvement, Priority - 3. Low 🔽

#431 Remove dfi.h from the source
  bin/h4_release_check.sh
  hdf/src/CMakeLists.txt
  hdf/src/Makefile.am
  hdf/src/df.h
  hdf/src/dfcomp.c
  hdf/src/dfi.h
  hdf/src/dfsd.c
  hdf/src/dfstubs.c
  hdf/src/hfile.h
  hdf/src/src.inc
  release_notes/RELEASE.txt
Labels: Component - C Library, Type - Deprecation / Removal, Priority - 2. Medium ⏹

#432 Drop support for MacFS
  hdf/src/hdfi.h
  hdf/src/hfile.h
  release_notes/RELEASE.txt
Labels: Component - C Library, Type - Deprecation / Removal, Priority - 3. Low 🔽

#433 Clean up command handling in hdp.c/h
  mfhdf/dumper/hdp.c
  mfhdf/dumper/hdp.h
Labels: Component - Tools, Type - Improvement, Priority - 3. Low 🔽

#436 Fix -Wdouble-promotion issues
  hdf/test/buffer.c
  hdf/test/chunks.c
  hdf/test/slab.c
  hdf/test/tvattr.c
  hdf/test/tvset.c
  hdf/util/he_cntrl.c
  hdf/util/vshow.c
  mfhdf/dumper/hdp_dump.c
  mfhdf/hdfimport/hdfimporttest.c
  mfhdf/hdiff/hdiff_array.c
  mfhdf/hdiff/hdiff_misc.c
  mfhdf/libsrc/netcdf.h.in
  mfhdf/ncdump/ncdump.c
  mfhdf/ncdump/vardata.c
  mfhdf/ncgen/generate.c
  mfhdf/ncgen/load.c
  mfhdf/nctest/val.c
  mfhdf/nctest/vartests.c
  mfhdf/test/cdftest.c
  mfhdf/test/hdftest.c
  mfhdf/test/tchunk.c
  mfhdf/test/tcoordvar.c
  mfhdf/test/tdatainfo.c
Labels: Component - C Library, Component - Tools, Component - netCDF, Component - Testing, Type - Improvement, Priority - 3. Low 🔽

#434 Remove atom hash table power-of-2 ifdefs
  hdf/src/atom.c
  hdf/src/atom.h
Labels: Component - C Library, Type - Improvement, Priority - 3. Low 🔽

#438 hdf/src: Remove defines of TESTING and code within ifdefs of TESTING
  hdf/src/cdeflate.c
  hdf/src/cnbit.c
  hdf/src/crle.c
  hdf/src/cskphuff.c
  hdf/src/hbitio.c
  hdf/src/hcomp.c
  hdf/src/hfile.c
  hdf/src/mstdio.c
  hdf/src/tbbt.c
Labels: Component - C Library, Type - Improvement, Priority - 3. Low 🔽

#437 dfsd.c: Remove redundant setting of ret_value and extra goto done in DFSDgetrange
  hdf/src/dfsd.c
Labels: Component - C Library, Type - Improvement, Priority - 3. Low 🔽

#435 Fix stack size warning in cdeflate.c
  hdf/src/cdeflate.c
  hdf/src/cdeflate.h
Labels: Component - C Library, Type - Improvement, Priority - 3. Low 🔽

#441 Fix getrusage in mcache.c
  config/cmake/h4config.h.in
  configure.ac
  hdf/src/mcache.c
Labels: Component - Build, Component - C Library, Type - Bug, Priority - 3. Low 🔽

#440 Create private hdf/src header list for CMake
  hdf/src/CMakeLists.txt
Labels: Component - Build, Component - C Library, Type - Improvement, Priority - 0. Blocker ⛔

#444 Correct CMake if-else in script and windows configuration
  config/cmake-presets/hidden-presets.json
  config/cmake/scripts/HDF4config.cmake
Labels: Component - Build, Component - Testing, Type - Bug, Priority - 0. Blocker ⛔

#447 Remove strdup implementation
  hdf/src/hdfalloc.c
  hdf/src/hproto.h
Labels: Component - C Library, Type - Improvement, Priority - 1. High 🔼

#448 Remove unnecessary `return;` statement at the end of two functions.
  hdf/src/mfan.c
  hdf/src/tbbt.c
Labels: Component - C Library, Priority - 3. Low 🔽
