Repository HDFGroup/hdf4, pull requests merged in 2023-06, with the labels that each got.

#360 Fix CMake variables, runTest APPLE, gen expressions.
  CMakeLists.txt
  config/cmake/HDFLibMacros.cmake
  config/cmake/HDFMacros.cmake
  config/cmake/JPEG/CMakeLists.txt
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/UseJavaSymlinks.cmake
  config/cmake/UserMacros/Windows_MT.cmake
  config/cmake/ZLIB/CMakeLists.txt
  config/cmake/grepTest.cmake
  config/cmake/jrunTest.cmake
  config/cmake/runTest.cmake
  config/cmake/scripts/CTestScript.cmake
  mfhdf/xdr/CMakeLists.txt
Labels: Component - Build, Type - Bug, Priority - 0. Blocker ⛔

#363 Update github actions with permissions and release workflows
  .github/workflows/clang-format-check.yml
  .github/workflows/clang-format-fix.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/codespell.yml
  .github/workflows/daily-build.yml
  .github/workflows/main.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
Labels: Component - Build, Component - Testing, Type - Improvement, Priority - 1. High 🔼

#358 Fix GH #355 mismatched macros
  .github/workflows/codespell.yml
  CMakeUserPresets.json
  bin/genparser
  config/toolchain/aarch64.cmake
  hdf/src/hdfi.h
  hdf/src/mfan.c
  hdf/src/mfan.h
  hdf/src/mfgrf.c
  hdf/src/vgp.c
  hdf/util/he.h
  java/src/jni/hdfsdsImp.c
  mfhdf/hrepack/hrepacktst.c
  mfhdf/ncdump/ncdump.1
  release_notes/RELEASE.txt
  release_notes/misc_docs.txt
Labels: Component - Java, Type - Bug, Priority - 0. Blocker ⛔

#365 Update daily-build workflows with fixes
  .github/workflows/clang-format-check.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/release.yml
Labels: Component - Build, Component - Testing, Type - Bug, Type - Improvement, Priority - 2. Medium ⏹

#367 Fix a java codespell issue
  java/test/TestH4.java
Labels: Component - Java, Type - Bug, Priority - 0. Blocker ⛔

#366 Fix H4_DFI_H endif.
  hdf/src/dfi.h
Labels: Component - Build, Confirmed, Type - Bug, Priority - 0. Blocker ⛔

#368 Update macOS GitHub actions to 13
  .github/workflows/main.yml
Labels: Component - Testing, Type - Improvement, Priority - 2. Medium ⏹

#370 sync daily build CI with latest
  .github/workflows/cmake-ctest.yml
  .github/workflows/daily-build.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
Labels: Component - Build, Component - Misc, Type - Improvement, Priority - 2. Medium ⏹

#371 Clean up ifdefs in atom.c/h
  hdf/src/atom.c
  hdf/src/atom.h
Labels: Component - C Library, Type - Improvement, Priority - 3. Low 🔽

#373 Add missing mfprivate.h to CMake
  mfhdf/libsrc/CMakeLists.txt
Labels: Component - Build, Type - Improvement, Priority - 3. Low 🔽

#372 Bring HDF5 format_source changes over
  bin/format_source
Labels: Component - Misc, Type - Improvement, Priority - 2. Medium ⏹

#376 Update CODEOWNERS to be like HDF5
  .github/CODEOWNERS
Labels: Component - Misc, Type - Task, Priority - 1. High 🔼

#375 Update the gcc version to 12 in GitHub actions
  .github/workflows/main.yml
Labels: Component - Build, Type - Improvement, Priority - 1. High 🔼

#377 Fix gfortran version check in Autotools
  config/gnu-fflags
  release_notes/RELEASE.txt
Labels: Component - Build, Component - Fortran, Type - Bug, Priority - 0. Blocker ⛔

#379 Move all 'warnings as errors' to warnings
  config/clang-warnings/error-general
  config/clang-warnings/general
  config/cmake/HDFCompilerFlags.cmake
  config/gnu-flags
  config/gnu-warnings/5
  config/gnu-warnings/7
  config/gnu-warnings/8
  config/gnu-warnings/error-5
  config/gnu-warnings/error-7
  config/gnu-warnings/error-8
  config/gnu-warnings/error-general
  config/gnu-warnings/general
Labels: Component - Build, Type - Improvement, Priority - 0. Blocker ⛔

#384 Add Fortran to CI
  .github/workflows/main.yml
Labels: Component - Fortran, Component - Testing, Type - Improvement, Priority - 0. Blocker ⛔

#380 Remove duplicated CFLAGS
  config/clang-flags
  config/gnu-flags
  config/intel-flags
Labels: Component - Build, Type - Bug, Priority - 1. High 🔼

#381 Remove orphan XDR prototypes
  mfhdf/xdr/xdr.h
Labels: Component - C Library, Component - XDR, Type - Deprecation / Removal, Priority - 3. Low 🔽

#382 Remove netlong and ncpos_t from xdrposix.c
  mfhdf/libsrc/xdrposix.c
Labels: Component - C Library, Component - XDR, Type - Deprecation / Removal, Priority - 3. Low 🔽

#386 Address all gcc -Walloc warnings
  hdf/src/vio.c
  mfhdf/test/tdatainfo.c
  mfhdf/test/tmixed_apis.c
Labels: Component - C Library, Type - Improvement, Priority - 3. Low 🔽

#383 Fix all gcc warnings in hrepack
  mfhdf/hrepack/hrepack.c
  mfhdf/hrepack/hrepack_check.c
  mfhdf/hrepack/hrepack_gr.c
  mfhdf/hrepack/hrepack_list.c
  mfhdf/hrepack/hrepack_sds.c
  mfhdf/hrepack/hrepack_vs.c
  mfhdf/hrepack/hrepacktst.c
Labels: Component - Tools, Component - Testing, Type - Improvement, Priority - 2. Medium ⏹

#388 Specify compiler in project command
  config/intel-fflags
  config/sanitizer/formatting.cmake
  hdf/CMakeLists.txt
  mfhdf/CMakeLists.txt
  mfhdf/dumper/CMakeLists.txt
  mfhdf/examples/CMakeLists.txt
  mfhdf/hdfimport/CMakeLists.txt
  mfhdf/hdiff/CMakeLists.txt
  mfhdf/hrepack/CMakeLists.txt
  mfhdf/ncdump/CMakeLists.txt
  mfhdf/ncgen/CMakeLists.txt
  mfhdf/nctest/CMakeLists.txt
  mfhdf/test/CMakeLists.txt
Labels: Component - Build, Priority - 0. Blocker ⛔

#389 fix CDash script command
  config/cmake/scripts/CTestScript.cmake
Labels: Component - Build, Type - Bug, Priority - 2. Medium ⏹

#392 Remove dead code behind #ifdefs
  hdf/src/hfile.c
  hdf/src/mfgr.c
  hdf/test/mgr.c
  hdf/test/rig.c
  hdf/test/testhdf.c
  mfhdf/dumper/hdp_list.c
  mfhdf/dumper/hdp_rig.c
Labels: Component - C Library, Component - Tools, Component - Testing, Type - Deprecation / Removal, Priority - 3. Low 🔽

#394 Clean up INT32DECODE macro
  hdf/src/hdfi.h
Labels: Component - C Library, Type - Improvement, Priority - 3. Low 🔽

#369 Fixed HDFFR-1609
  hdf/src/hextelt.c
  mfhdf/test/texternal.c
  release_notes/RELEASE.txt
Labels: Component - C Library, Type - Bug, Priority - 0. Blocker ⛔

#396 Fix "failing" netCDF tests
  mfhdf/test/tncvargetfill.c
Labels: Component - Testing, Type - Bug, Priority - 1. High 🔼

#397 Test code improvement in tncvargetfill
  mfhdf/test/tncvargetfill.c
Labels: Component - Testing, Type - Improvement, Priority - 1. High 🔼

#400 Organize CMake/Autotools options in main.yml
  .github/workflows/main.yml
Labels: Component - Testing, Type - Improvement, Priority - 3. Low 🔽

#401 PowerPC Linux uses the standard flags in Autotools
  config/powerpc64-linux-gnu
Labels: Component - Build, Type - Bug, Priority - 0. Blocker ⛔

#402 Fix PowerPC Linux gcc flags to be like master
  config/powerpc64-linux-gnu
Labels: Component - Build, Type - Improvement, Priority - 0. Blocker ⛔

#413 Fix szip packaging and release note file
  CMakeFilters.cmake
  CMakeInstallation.cmake
  config/cmake/HDFLibMacros.cmake
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/ZLIB/CMakeLists.txt
  config/cmake/hdf4-config.cmake.in
  config/toolchain/aarch64.cmake
  release_notes/RELEASE.txt
Labels: Component - Build, Type - Bug, Priority - 0. Blocker ⛔

#415 fix windows valid VS versions
  config/cmake/scripts/HDF4config.cmake
Labels: Component - Build, Priority - 0. Blocker ⛔
