Repository HDFGroup/hdf4, pull requests merged in 2023-07, with the labels that each got.

#414 Fix szip packaging
  CMakeFilters.cmake
  CMakeInstallation.cmake
  config/cmake/HDFLibMacros.cmake
  config/cmake/hdf4-config.cmake.in
  config/toolchain/aarch64.cmake
Labels: Component - Build, Type - Bug, Priority - 0. Blocker ⛔

#416 Master fix script
  config/cmake/examples/CTestScript.cmake
  config/cmake/scripts/CTestScript.cmake
  config/cmake/scripts/HDF4config.cmake
Labels: Component - Build, Priority - 0. Blocker ⛔

#391 Add release workflow, refactor existing scripts
  .gitattributes
  .github/workflows/daily-build.yml
  .github/workflows/release-files.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
  CMakeInstallation.cmake
  README.md
  bin/bbrelease
  bin/h4vers
  bin/release
  config/cmake/JPEG/CMakeLists.txt
Labels: Component - Build, Component - Misc, Type - Improvement, Type - New Feature, Priority - 1. High 🔼

#417 snapshot name save in file
  .github/workflows/release-files.yml
  bin/release
Labels: Component - Documentation, Component - Misc, Component - Testing, Type - Improvement, Priority - 0. Blocker ⛔

#418 Add 4.2.16-2 to release schedule
  doc/img/release-schedule.plantuml
  doc/img/release-schedule.png
Labels: Component - Documentation, Type - Task, Priority - 1. High 🔼
