Repository HDFGroup/hdf4, pull requests merged in 2023-12, with the labels that each got.

#460 Removed most NCSA references
  hdf/src/dffunc.inc
  hdf/src/hdf.inc
  hdf/src/hfile.c
  hdf/src/hfile.h
  hdf/src/src.inc
  hdf/src/vgp.c
  hdf/test/egfhi.f
  hdf/util/fp2hdf.c
  hdf/util/hdf24to8.c
  mfhdf/hdfimport/hdfimport.c
  mfhdf/hdiff/hdiff_dim.h
  mfhdf/hdiff/hdiff_list.h
  mfhdf/hdiff/hdiff_mattbl.h
  mfhdf/hdiff/hdiff_table.h
  mfhdf/hrepack/hrepack_check.c
  mfhdf/hrepack/hrepack_dim.h
  mfhdf/hrepack/hrepack_vg.h
  mfhdf/libsrc/nssdc.c
Labels: Component - Documentation, Component - Misc, Type - Deprecation / Removal, Priority - 1. High 🔼

#461 add doxygen basics
  .clang-format
  .github/workflows/autotools.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/cmake.yml
  .github/workflows/codespell.yml
  .github/workflows/intel-auto.yml
  .github/workflows/intel-cmake.yml
  .github/workflows/main-cmake.yml
  .github/workflows/release-files.yml
  CMakeInstallation.cmake
  CMakeLists.txt
  Makefile.am
  bin/release
  config/cmake-presets/hidden-presets.json
  config/cmake/HDFCompilerFlags.cmake
  config/cmake/HDFMacros.cmake
  config/cmake/patch.xml.in
  configure.ac
  doxygen/CMakeLists.txt
  doxygen/Doxyfile.in
  doxygen/aliases
  doxygen/dox/About.dox
  doxygen/dox/GettingStarted.dox
  doxygen/dox/Glossary.dox
  doxygen/dox/Overview.dox
  doxygen/dox/UsersGuide.dox
  doxygen/dox/rm-template.dox
  doxygen/dox/userguide/appendix.dox
  doxygen/dox/userguide/chap1.dox
  doxygen/dox/userguide/chap10.dox
  doxygen/dox/userguide/chap11.dox
  doxygen/dox/userguide/chap12.dox
  doxygen/dox/userguide/chap13.dox
  doxygen/dox/userguide/chap14.dox
  doxygen/dox/userguide/chap15.dox
  doxygen/dox/userguide/chap16.dox
  doxygen/dox/userguide/chap2.dox
  doxygen/dox/userguide/chap3.dox
  doxygen/dox/userguide/chap4.dox
  doxygen/dox/userguide/chap5.dox
  doxygen/dox/userguide/chap6.dox
  doxygen/dox/userguide/chap7.dox
  doxygen/dox/userguide/chap8.dox
  doxygen/dox/userguide/chap9.dox
  doxygen/hdf4_footer.html
  doxygen/hdf4_header.html
  doxygen/hdf4_navtree_hacks.js
  doxygen/hdf4doxy.css
  doxygen/hdf4doxy_layout.xml
  doxygen/img/HDFG-logo.png
  hdf/src/CMakeLists.txt
  java/CMakeLists.txt
  m4/ax_prog_doxygen.m4
  mfhdf/libsrc/CMakeLists.txt
  release_notes/HISTORY.txt
  release_notes/INSTALL_CMake.txt
  release_notes/RELEASE.txt
Labels: Component - Build, Component - Documentation, Type - New Feature, Priority - 3. Low 🔽

#462 Fix incorrect filename
  .github/workflows/cmake-ctest.yml
Labels: Component - Build, Component - Misc, Type - Bug, Priority - 0. Blocker ⛔

#463 yet another hdf5 in hdf4
  .github/workflows/cmake-ctest.yml
Labels: Component - Build, Component - Misc, Type - Bug, Priority - 0. Blocker ⛔

#464 Correct compression libs from GIT and JPEG CMake
  .clang-format
  CMakeFilters.cmake
  CMakePresets.json
  config/cmake/HDFMacros.cmake
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/cacheinit.cmake
  config/cmake/hdf4-config.cmake.in
  release_notes/INSTALL_CMake.txt
Labels: Component - Build, Component - Misc, Type - Bug, Type - Improvement, Priority - 0. Blocker ⛔
