Repository HDFGroup/hdf4, pull requests merged in 2023-08, with the labels that each got.

#420 Windows runtime is deployed to bin folder
  java/src/jni/CMakeLists.txt
Labels: Component - Build, Component - Java, Type - Bug, Priority - 1. High 🔼

#422 Add a GitHub badge for HDF-EOS
  README.md
Labels: Component - Misc, Type - Task, Priority - 3. Low 🔽

#421 Add HDF4 4.3.0 to the release schedule
  README.md
  doc/img/release-schedule.plantuml
  doc/img/release-schedule.png
Labels: Component - Documentation, Type - Task, Priority - 1. High 🔼
