Repository HDFGroup/hdf4, pull requests merged in 2024-08, with the labels that each got.

#735 Correct the uncompress of the doxygen file
  .github/workflows/publish-release.yml
Labels: Component - Misc, Type - Bug, Priority - 0. Blocker ⛔

#737 Add mac dmg binary and remove old macos-13 workflows
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/main-cmake.yml
  .github/workflows/release-files.yml
  .github/workflows/remove-files.yml
  CMakeInstallation.cmake
Labels: Component - Build, Component - Misc, Type - Improvement, Priority - 2. Medium ⏹

#738 Add codesign action
  .github/workflows/cmake-ctest.yml
  .github/workflows/daily-build.yml
Labels: Component - Misc, Type - New Feature, Priority - 0. Blocker ⛔

#739 Only msi can be signed
  .github/workflows/cmake-ctest.yml
Labels: Component - Misc, Type - Improvement, Priority - 0. Blocker ⛔

#740 Change osx usage to macos
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/daily-build.yml
  .github/workflows/main-cmake.yml
  .github/workflows/release-files.yml
  .github/workflows/remove-files.yml
  CMakePresets.json
  HDF4Examples/CMakePresets.json
Labels: Component - Misc, Type - Bug, Type - Improvement, Priority - 1. High 🔼

#742 Change logic for checking secrets exists
  .github/workflows/cmake-ctest.yml
Labels: Component - Misc, Type - Bug, Priority - 0. Blocker ⛔

#743 Fix typo unzipf in publish-release workflow
  .github/workflows/publish-release.yml
Labels: Component - Misc, Type - Bug, Priority - 1. High 🔼

#744 Check job level secret
  .github/workflows/cmake-ctest.yml
Labels: Component - Misc, Type - Bug, Priority - 0. Blocker ⛔

#745 Check current version before remove files
  .github/workflows/cmake-ctest.yml
  .github/workflows/daily-build.yml
Labels: Component - Misc, Type - Bug, Priority - 1. High 🔼

#746 Use correct folder for signing Intel binaries
  .github/workflows/cmake-ctest.yml
Labels: Type - Bug, Priority - 0. Blocker ⛔

#749 Fix typo in command
  .github/workflows/cmake-ctest.yml
Labels: Component - Misc, Type - Bug, Priority - 0. Blocker ⛔

#750 Add mac notarization
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-ctest.yml
  CMakePresets.json
  HDF4Examples/CMakePresets.json
  HDF4Examples/config/cmake-presets/hidden-presets.json
  config/cmake-presets/hidden-presets.json
Labels: Component - Build, Component - Misc, Type - Improvement, Priority - 0. Blocker ⛔

#753 Add step to show result of notarize step
  .github/workflows/cmake-ctest.yml
Labels: Component - Misc, Type - Bug, Priority - 0. Blocker ⛔

#754 Add verify codesign steps
  .github/workflows/cmake-ctest.yml
  config/cmake/CPack.Info.plist.in
  config/cmake/distribution.entitlements
Labels: Component - Misc, Type - Bug, Priority - 0. Blocker ⛔

#755 Rework getting id for notary log
  .github/workflows/cmake-ctest.yml
Labels: Component - Misc, Type - Bug, Priority - 0. Blocker ⛔

#756 Use correct contexts
  .github/workflows/cmake-ctest.yml
Labels: Component - Misc, Type - Bug, Priority - 0. Blocker ⛔

#757 Add signing and list of files to be signed for packaging
  .github/workflows/cmake-ctest.yml
  CMakeInstallation.cmake
  CMakeLists.txt
  config/cmake/SignPackageFiles.cmake
  hdf/fortran/CMakeLists.txt
  hdf/src/CMakeLists.txt
  hdf/util/CMakeLists.txt
  mfhdf/fortran/CMakeLists.txt
  mfhdf/hdfimport/CMakeLists.txt
  mfhdf/hdiff/CMakeLists.txt
  mfhdf/hdp/CMakeLists.txt
  mfhdf/hrepack/CMakeLists.txt
  mfhdf/src/CMakeLists.txt
Labels: Component - Build, Component - Misc, Type - Improvement, Type - New Feature, Priority - 0. Blocker ⛔

#758 Use existing vars and cpack requires CPACK prefix
  CMakeInstallation.cmake
  CMakeLists.txt
  config/cmake/SignPackageFiles.cmake
  hdf/fortran/CMakeLists.txt
  hdf/src/CMakeLists.txt
  hdf/util/CMakeLists.txt
  mfhdf/fortran/CMakeLists.txt
  mfhdf/hdfimport/CMakeLists.txt
  mfhdf/hdiff/CMakeLists.txt
  mfhdf/hdp/CMakeLists.txt
  mfhdf/hrepack/CMakeLists.txt
  mfhdf/src/CMakeLists.txt
Labels: Component - Build, Component - Misc, Type - Bug, Type - Improvement, Priority - 0. Blocker ⛔

#759 Correct ENV usage
  CMakeInstallation.cmake
  bin/cmakehdf4
  config/cmake/SignPackageFiles.cmake
  config/cmake/examples/CTestScript.cmake
  config/cmake/scripts/CTestScript.cmake
Labels: Component - Build, Component - Misc, Type - Bug, Priority - 0. Blocker ⛔

#760 Fix windows paths and compare check
  .github/workflows/cmake-ctest.yml
  CMakeInstallation.cmake
  config/cmake/SignPackageFiles.cmake
Labels: Component - Build, Component - Misc, Type - Bug, Priority - 0. Blocker ⛔
