Repository HDFGroup/hdf4, pull requests merged in 2024-03, with the labels that each got.

#655 Clean out RELEASE.txt after 4.3.0 release
  release_notes/RELEASE.txt
Labels: Component - Documentation, Type - Task, Priority - 0. Blocker ⛔

#657 Update the HISTORY file w/ 4.3.0 info
  release_notes/HISTORY.txt
Labels: Component - Documentation, Type - Task, Priority - 0. Blocker ⛔

#659 Update README.md after 4.3.0 release
  README.md
Labels: Component - Documentation, Type - Task, Priority - 1. High 🔼

#658 Clean up paths-ignore in GitHub CI
  .github/workflows/hdfeos2.yml
  .github/workflows/main.yml
  .github/workflows/msys2-auto.yml
  .github/workflows/netcdf.yml
  .github/workflows/ppc64.yml
Labels: Component - Testing, Type - Improvement, Priority - 1. High 🔼

#656 Remove the ncdump and ncgen tools
  .github/workflows/msys2-auto.yml
  .github/workflows/netcdf.yml
  CMakeLists.txt
  bin/format_source
  bin/genparser
  bin/h4_release_check.sh
  config/cmake/libhdf4.settings.cmake.in
  configure.ac
  libhdf4.settings.in
  mfhdf/CMakeLists.txt
  mfhdf/Makefile.am
  mfhdf/fortran/ftest.f.in
  mfhdf/hdiff/hdiff.h
  mfhdf/ncdump/CMakeLists.txt
  mfhdf/ncdump/CMakeTests.cmake
  mfhdf/ncdump/Makefile.am
  mfhdf/ncdump/dumplib.c
  mfhdf/ncdump/dumplib.h
  mfhdf/ncdump/ncdump.1
  mfhdf/ncdump/ncdump.c
  mfhdf/ncdump/ncdump.h
  mfhdf/ncdump/test0.cdl
  mfhdf/ncdump/testncdump.sh.in
  mfhdf/ncdump/vardata.c
  mfhdf/ncdump/vardata.h
  mfhdf/ncgen/CMakeLists.txt
  mfhdf/ncgen/CMakeTests.cmake
  mfhdf/ncgen/Makefile.am
  mfhdf/ncgen/README
  mfhdf/ncgen/close.c
  mfhdf/ncgen/escapes.c
  mfhdf/ncgen/generate.c
  mfhdf/ncgen/generic.h
  mfhdf/ncgen/genlib.c
  mfhdf/ncgen/genlib.h
  mfhdf/ncgen/getfill.c
  mfhdf/ncgen/init.c
  mfhdf/ncgen/load.c
  mfhdf/ncgen/main.c
  mfhdf/ncgen/ncgen.1
  mfhdf/ncgen/ncgen.h
  mfhdf/ncgen/ncgen.l
  mfhdf/ncgen/ncgen.y
  mfhdf/ncgen/ncgentab.c
  mfhdf/ncgen/ncgentab.h
  mfhdf/ncgen/ncgenyy.c
  mfhdf/ncgen/test0.cdl
  mfhdf/ncgen/testncgen.sh.in
  mfhdf/nctest/Makefile.am
  release_notes/INSTALL_CMake.txt
  release_notes/INSTALL_WINDOWS.txt
  release_notes/RELEASE.txt
Labels: Component - Tools, Component - netCDF, Type - Deprecation / Removal, Priority - 0. Blocker ⛔

#662 Fix broken bin/format_source
  bin/format_source
Labels: Component - Misc, Type - Bug, Priority - 0. Blocker ⛔

#661 Remove unused linked list code
  hdf/src/CMakeLists.txt
  hdf/src/Makefile.am
  hdf/src/hfile_priv.h
  hdf/src/linklist.c
  hdf/src/linklist_priv.h
Labels: Component - C Library, Type - Deprecation / Removal, Priority - 2. Medium ⏹

#660 Add subdir-objects to AM_INIT_AUTOMAKE
  autogen.sh
  configure.ac
Labels: Component - Build, Type - Improvement, Priority - 2. Medium ⏹

#663 Rework atexit handling code
  hdf/src/CMakeLists.txt
  hdf/src/Makefile.am
  hdf/src/glist.c
  hdf/src/glist_priv.h
  hdf/src/hfile.c
Labels: Component - C Library, Type - Deprecation / Removal, Type - Improvement, Priority - 2. Medium ⏹

#664 Add checksums and NEWSLETTER to releases
  .github/workflows/abi-report.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/daily-build.yml
  .github/workflows/release-files.yml
  .github/workflows/release.yml
  .github/workflows/remove-files.yml
  .github/workflows/tarball.yml
  config/cmake/HDFMacros.cmake
  config/cmake/README.txt.cmake.in
  config/toolchain/clang.cmake
  release_notes/INSTALL_CMake.txt
Labels: Component - Build, Component - Documentation, Component - Misc, Type - Improvement, Priority - 1. High 🔼

#668 Update README.md
  README.md
Labels: Component - Documentation, Type - Improvement, Priority - 2. Medium ⏹

#667 Clean up bin/format_source
  bin/format_source
Labels: Component - Misc, Type - Improvement, Priority - 2. Medium ⏹

#666 Separate atexit code to new files
  hdf/src/CMakeLists.txt
  hdf/src/Makefile.am
  hdf/src/hfile.c
  hdf/src/hfile_atexit.c
  hdf/src/hfile_atexit_priv.h
  hdf/test/CMakeLists.txt
  hdf/test/Makefile.am
  hdf/test/file_atexit.c
  hdf/test/testhdf.c
  hdf/test/tproto.h
Labels: Component - C Library, Component - Testing, Type - Improvement, Priority - 2. Medium ⏹

#669 Rename mfhdf/libsrc to mfhdf/src
  CMakeLists.txt
  config/commence.am
  configure.ac
  hdf/src/htags.h
  java/src/hdf/hdflib/HDFConstants.java
  java/src/jni/Makefile.am
  java/test/junit.sh.in
  mfhdf/Makefile.am
  mfhdf/dumper/Makefile.am
  mfhdf/dumper/README
  mfhdf/fortran/CMakeLists.txt
  mfhdf/fortran/Makefile.am
  mfhdf/hdfimport/Makefile.am
  mfhdf/hdiff/Makefile.am
  mfhdf/hrepack/Makefile.am
  mfhdf/nctest/Makefile.am
  mfhdf/nctest/nctest.lnk
  mfhdf/src/CMakeLists.txt
  mfhdf/src/Makefile.am
  mfhdf/src/array.c
  mfhdf/src/attr.c
  mfhdf/src/cdf.c
  mfhdf/src/dim.c
  mfhdf/src/error.c
  mfhdf/src/error_priv.h
  mfhdf/src/file.c
  mfhdf/src/globdef.c
  mfhdf/src/h4_xdr.c
  mfhdf/src/h4_xdr_priv.h
  mfhdf/src/hdf2netcdf.h
  mfhdf/src/hdfnctest.c
  mfhdf/src/hdfsds.c
  mfhdf/src/iarray.c
  mfhdf/src/mf_priv.h
  mfhdf/src/mfdatainfo.c
  mfhdf/src/mfdatainfo.h
  mfhdf/src/mfhdf.h
  mfhdf/src/mfsd.c
  mfhdf/src/nc_priv.h
  mfhdf/src/netcdf.h.in
  mfhdf/src/nssdc.c
  mfhdf/src/putget.c
  mfhdf/src/putgetg.c
  mfhdf/src/sharray.c
  mfhdf/src/string.c
  mfhdf/src/var.c
  mfhdf/test/Makefile.am
  mfhdf/test/tszip.c
Labels: Component - Build, Component - C Library, Type - Improvement, Priority - 2. Medium ⏹

#665 Rename file1.c test to file_limits.c
  hdf/test/CMakeLists.txt
  hdf/test/Makefile.am
  hdf/test/file_limits.c
  hdf/test/testhdf.c
  hdf/test/tproto.h
Labels: Component - Testing, Type - Improvement, Priority - 3. Low 🔽

#678 Remove Quincey from CODEOWNERS
  .github/CODEOWNERS
Labels: Component - Misc, Type - Task, Priority - 3. Low 🔽

#676 Use C99 in hdf/test/macros.c
  hdf/test/macros.c
Labels: Component - Testing, Type - Improvement, Priority - 3. Low 🔽

#673 Remove comments about multi-threading
  hdf/src/hbitio.c
Labels: Component - C Library, Type - Improvement, Priority - 3. Low 🔽

#677 Clean up atom code
  hdf/src/atom.c
  hdf/src/atom_priv.h
Labels: Component - C Library, Type - Improvement, Priority - 3. Low 🔽

#672 Remove MODIFICATION HISTORY comments
  hdf/src/vg.c
  hdf/test/conv.c
  hdf/test/gentest.c
  hdf/test/nbit.c
Labels: Component - Testing, Type - Improvement, Priority - 3. Low 🔽

#671 Rename hdf/test/tproto.h to testhdf.h
  hdf/test/an.c
  hdf/test/anfile.c
  hdf/test/bitio.c
  hdf/test/blocks.c
  hdf/test/chunks.c
  hdf/test/comp.c
  hdf/test/conv.c
  hdf/test/extelt.c
  hdf/test/file.c
  hdf/test/file_atexit.c
  hdf/test/file_limits.c
  hdf/test/litend.c
  hdf/test/macros.c
  hdf/test/man.c
  hdf/test/mgr.c
  hdf/test/nbit.c
  hdf/test/rig.c
  hdf/test/sdmms.c
  hdf/test/sdnmms.c
  hdf/test/sdstr.c
  hdf/test/slab.c
  hdf/test/tbv.c
  hdf/test/tdatainfo.c
  hdf/test/tdfr8.c
  hdf/test/testhdf.c
  hdf/test/testhdf.h
  hdf/test/tmgrattr.c
  hdf/test/tree.c
  hdf/test/tusejpegfuncs.c
  hdf/test/tvattr.c
  hdf/test/tvnameclass.c
  hdf/test/tvset.c
  hdf/test/tvsfpack.c
  hdf/test/vers.c
Labels: Component - Testing, Type - Improvement, Priority - 3. Low 🔽

#674 Rename release_notes to release_docs
  .github/workflows/hdfeos2.yml
  .github/workflows/main.yml
  .github/workflows/msys2-auto.yml
  .github/workflows/netcdf.yml
  .github/workflows/ppc64.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
  CMakeInstallation.cmake
  README.md
  bin/h4vers
  bin/release
  release_docs/HISTORY.txt
  release_docs/INSTALL
  release_docs/INSTALL_Auto.txt
  release_docs/INSTALL_CMake.txt
  release_docs/INSTALL_WINDOWS.txt
  release_docs/NEWSLETTER.txt
  release_docs/NEWSLETTER_README.txt
  release_docs/OLD/bugs_fixed.txt
  release_docs/OLD/misc_docs.txt
  release_docs/RELEASE.txt
  release_docs/USING_CMake_Examples.txt
  release_docs/USING_HDF4_CMake.txt
  release_docs/USING_HDF4_VS.txt
Labels: Component - Documentation, Type - Improvement, Priority - 3. Low 🔽

#679 Do not enable szip for sanitizer runs
  config/cmake/mccacheinit.cmake
Labels: Component - Misc, Component - Testing, Type - Bug, Priority - 0. Blocker ⛔

#680 Correct test commands when used with memchecking
  mfhdf/hdfimport/CMakeTests.cmake
  mfhdf/hdiff/CMakeTests.cmake
Labels: Component - Testing, Type - Bug, Priority - 2. Medium ⏹

#681 ignore userpresets file and don't force clang Fortran
  .gitignore
  config/toolchain/clang.cmake
Labels: Component - Misc, Component - Testing, Type - Bug, Priority - 1. High 🔼

#683 Clean up mfhdf/src
  mfhdf/src/array.c
  mfhdf/src/attr.c
  mfhdf/src/cdf.c
  mfhdf/src/dim.c
  mfhdf/src/file.c
  mfhdf/src/hdf2netcdf.h
  mfhdf/src/hdfsds.c
  mfhdf/src/iarray.c
  mfhdf/src/mfdatainfo.c
  mfhdf/src/mfsd.c
  mfhdf/src/nc_priv.h
  mfhdf/src/nssdc.c
  mfhdf/src/putget.c
  mfhdf/src/putgetg.c
  mfhdf/src/string.c
  mfhdf/src/var.c
Labels: Component - C Library, Component - netCDF, Type - Improvement, Priority - 2. Medium ⏹

#685 Fix typo: `Verbocity` -> `Verbosity` in conv.c and macros.c
  hdf/test/conv.c
  hdf/test/macros.c
Labels: Component - C Library, Type - Bug, Priority - 2. Medium ⏹

#682 Rename incorrectly named option
  config/cmake/mccacheinit.cmake
  hdf/util/CMakeTests.cmake
  mfhdf/hdfimport/CMakeTests.cmake
  mfhdf/hdiff/CMakeTests.cmake
  mfhdf/hdp/CMakeTests.cmake
  mfhdf/hrepack/CMakeTests.cmake
  release_docs/INSTALL_CMake.txt
  release_docs/RELEASE.txt
Labels: Component - Testing, Type - Task, Priority - 1. High 🔼

#686 Remove Void type (--> uint8_t)
  mfhdf/src/array.c
  mfhdf/src/attr.c
  mfhdf/src/cdf.c
  mfhdf/src/dim.c
  mfhdf/src/hdfsds.c
  mfhdf/src/mfsd.c
  mfhdf/src/nc_priv.h
  mfhdf/src/nssdc.c
  mfhdf/src/putget.c
  mfhdf/src/putgetg.c
  mfhdf/src/var.c
Labels: Component - C Library, Component - netCDF, Type - Deprecation / Removal, Priority - 2. Medium ⏹

#687 Change to use tarball from release branch and create tag
  .github/workflows/cmake-ctest.yml
  .github/workflows/daily-build.yml
  .github/workflows/release-files.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
Labels: Component - Build, Component - Misc, Type - Improvement, Type - New Feature, Priority - 0. Blocker ⛔

#690 Remove .indent.pro file
  hdf/src/.indent.pro
Labels: Component - C Library, Type - Deprecation / Removal, Priority - 3. Low 🔽

#693 Change how library tests run
  configure.ac
  hdf/test/CMakeTests.cmake
  mfhdf/test/CMakeTests.cmake
  mfhdf/test/Makefile.am
  mfhdf/test/testmfhdf.sh.in
Labels: Component - Testing, Type - Improvement, Priority - 1. High 🔼

#695 Minor float/float32/double/float64 cleanup
  hdf/src/dfgr.c
  hdf/src/dfimcomp.c
  hdf/src/dfr8.c
  hdf/src/dfsd.c
  hdf/test/an.c
  hdf/test/conv.c
  hdf/test/litend.c
  hdf/test/man.c
  hdf/test/sdmms.c
  hdf/test/slab.c
  hdf/test/tvattr.c
  hdf/test/tvset.c
  hdf/test/tvsfpack.c
  hdf/util/fp2hdf.c
  hdf/util/fptest.c
  hdf/util/hdf8to24.c
  mfhdf/hdfimport/hdfimporttest.c
  mfhdf/hdp/hdp_dump.c
  mfhdf/nctest/vardef.c
  mfhdf/test/tattdatainfo.c
  mfhdf/test/tattributes.c
  mfhdf/test/tchunk.c
Labels: Component - C Library, Component - Tools, Component - Testing, Type - Improvement, Priority - 3. Low 🔽

#696 Remove commented-out test in testutil.sh.in
  hdf/util/testutil.sh.in
Labels: Component - Testing, Type - Improvement, Priority - 3. Low 🔽

#697 Remove dead fp2hdf code
  hdf/util/README
  hdf/util/README.TST
  hdf/util/README.fp2hdf
  hdf/util/README.fp2hdf.test
  hdf/util/fp2hdf.c
  hdf/util/fp2hdf.input1
  hdf/util/fp2hdf.input1-32
  hdf/util/fp2hdf.out1
  hdf/util/fp2hdf.out1-32
  hdf/util/fp2hdf.out2
  hdf/util/fp2hdf.out2-32
  hdf/util/fp2hdf.test
  hdf/util/fp2hdf.test.result
  hdf/util/fptest.c
Labels: Component - Tools, Type - Deprecation / Removal, Priority - 3. Low 🔽

#698 Minor cleanup in mfhdf test code
  mfhdf/test/hdftest.h
  mfhdf/test/tattdatainfo.c
  mfhdf/test/tattributes.c
  mfhdf/test/tdatainfo.c
  mfhdf/test/tsdsprops.c
Labels: Component - Testing, Type - Improvement, Priority - 1. High 🔼

#700 Re-enable test_sd() in hdftest
  mfhdf/test/hdftest.c
  mfhdf/test/tsd.c
  release_docs/RELEASE.txt
Labels: Component - Testing, Type - Improvement, Priority - 0. Blocker ⛔

#704 Correct the names of the GH release binaries to match contents
  .github/workflows/abi-report.yml
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/daily-build.yml
  .github/workflows/release-files.yml
  .github/workflows/release.yml
  .github/workflows/remove-files.yml
  .github/workflows/tarball.yml
Labels: Component - Misc, Type - Improvement, Priority - 1. High 🔼

#705 Workflow cleanup and cygwin fixes
  .github/workflows/aocc-auto.yml
  .github/workflows/aocc-cmake.yml
  .github/workflows/autotools.yml
  .github/workflows/cmake.yml
  .github/workflows/cygwin-auto.yml
  .github/workflows/cygwin-cmake.yml
  .github/workflows/cygwin.yml
  .github/workflows/intel-cmake.yml
  .github/workflows/main-auto.yml
  .github/workflows/main-cmake.yml
  .github/workflows/main.yml
  .github/workflows/mingw-cmake.yml
  .github/workflows/msys2-auto.yml
  .github/workflows/msys2-cmake.yml
  .github/workflows/nvhpc-auto.yml
  .github/workflows/nvhpc-cmake.yml
  config/cmake/ConfigureChecks.cmake
  config/cmake/scripts/CTestScript.cmake
  configure.ac
Labels: Component - Build, Component - Misc, Type - Improvement

#706 Fix off-by-1 max file name len in dfp/dfr8
  hdf/src/dfp.c
  hdf/src/dfr8.c
Labels: Component - C Library, Type - Bug, Priority - 2. Medium ⏹

#708 Clean up hrepack code
  mfhdf/hrepack/hrepack.c
  mfhdf/hrepack/hrepack_an.c
  mfhdf/hrepack/hrepack_check.c
  mfhdf/hrepack/hrepack_dim.c
  mfhdf/hrepack/hrepack_gr.c
  mfhdf/hrepack/hrepack_list.c
  mfhdf/hrepack/hrepack_lsttable.c
  mfhdf/hrepack/hrepack_lsttable.h
  mfhdf/hrepack/hrepack_main.c
  mfhdf/hrepack/hrepack_opttable.c
  mfhdf/hrepack/hrepack_parse.c
  mfhdf/hrepack/hrepack_sds.c
  mfhdf/hrepack/hrepack_utils.c
  mfhdf/hrepack/hrepack_vs.c
  mfhdf/hrepack/hrepacktst.c
Labels: Component - Tools, Type - Improvement, Priority - 2. Medium ⏹

#709 Clean up hdiff code
  mfhdf/hdiff/hdiff.c
  mfhdf/hdiff/hdiff_array.c
  mfhdf/hdiff/hdiff_dim.c
  mfhdf/hdiff/hdiff_gattr.c
  mfhdf/hdiff/hdiff_gr.c
  mfhdf/hdiff/hdiff_list.c
  mfhdf/hdiff/hdiff_main.c
  mfhdf/hdiff/hdiff_mattbl.c
  mfhdf/hdiff/hdiff_mattbl.h
  mfhdf/hdiff/hdiff_misc.c
  mfhdf/hdiff/hdiff_sds.c
  mfhdf/hdiff/hdiff_table.c
  mfhdf/hdiff/hdiff_table.h
  mfhdf/hdiff/hdiff_vs.c
  mfhdf/hdiff/hdifftst.c
Labels: Component - Tools, Type - Improvement, Priority - 2. Medium ⏹

#710 Warning cleanup in hdf/src and test & mfhdf/src
  hdf/src/dfan.c
  hdf/src/dfp.c
  hdf/src/dfsd.c
  hdf/src/dynarray.c
  hdf/src/hbitio.c
  hdf/src/hbuffer.c
  hdf/src/hchunks.c
  hdf/src/hfiledd.c
  hdf/src/hkit.c
  hdf/src/mfgr.c
  hdf/test/an.c
  mfhdf/src/putget.c
Labels: Component - C Library, Component - Testing, Type - Improvement, Priority - 1. High 🔼

#711 Clean up warnings in the hdp tool
  mfhdf/hdp/hdp.c
  mfhdf/hdp/hdp.h
  mfhdf/hdp/hdp_dump.c
  mfhdf/hdp/hdp_gr.c
  mfhdf/hdp/hdp_list.c
  mfhdf/hdp/hdp_rig.c
  mfhdf/hdp/hdp_sds.c
  mfhdf/hdp/hdp_util.c
  mfhdf/hdp/hdp_vd.c
  mfhdf/hdp/hdp_vg.c
  mfhdf/hdp/show.c
Labels: Component - Tools, Type - Improvement, Priority - 2. Medium ⏹

#712 Fixed many warnings
  hdf/src/vattr.c
  hdf/src/vconv.c
  hdf/src/vg.c
  hdf/src/vgp.c
  hdf/src/vio.c
  hdf/src/vparse.c
  hdf/test/comp.c
  hdf/test/man.c
  hdf/test/nbit.c
  hdf/test/rig.c
  hdf/test/tdatainfo.c
  hdf/test/tmgrattr.c
  hdf/test/tusejpegfuncs.c
  hdf/test/tvattr.c
  hdf/test/tvset.c
  hdf/util/decompress.c
  hdf/util/gif2hdf.c
  hdf/util/gifread.c
  hdf/util/hdf24to8.c
  hdf/util/hdf2gif.c
  hdf/util/hdf8to24.c
  hdf/util/hdfcomp.c
  hdf/util/hdfls.c
  hdf/util/hdfpack.c
  hdf/util/he_cntrl.c
  hdf/util/he_disp.c
  hdf/util/he_file.c
  hdf/util/he_main.c
  hdf/util/he_proto.h
  hdf/util/vshow.c
  mfhdf/src/cdf.c
  mfhdf/src/file.c
  mfhdf/src/hdfsds.c
  mfhdf/src/mfdatainfo.c
  mfhdf/src/mfsd.c
  mfhdf/src/putget.c
  mfhdf/src/string.c
  mfhdf/src/var.c
  mfhdf/test/hdftest.h
  mfhdf/test/tattdatainfo.c
  mfhdf/test/tcoordvar.c
  mfhdf/test/tdatainfo.c
  mfhdf/test/texternal.c
  mfhdf/test/tmixed_apis.c
  mfhdf/test/tncvargetfill.c
  mfhdf/test/tunlim.c
  mfhdf/test/tutils.c
Labels: Component - C Library, Component - Tools, Component - Testing, Type - Improvement, Priority - 2. Medium ⏹
