Repository HDFGroup/hdf4, pull requests merged in 2024-02, with the labels that each got.

#478 Master add bintest
  .github/dependabot.yml
  .github/workflows/clang-format-check.yml
  .github/workflows/clang-format-fix.yml
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/cmake.yml
  .github/workflows/codespell.yml
  .github/workflows/daily-build.yml
  .github/workflows/intel-cmake.yml
  .github/workflows/main-cmake-mingw.yml
  .github/workflows/main-cmake.yml
  .github/workflows/main.yml
  .github/workflows/ppc64.yml
  .github/workflows/release.yml
  CMakeFilters.cmake
  CMakeInstallation.cmake
  CMakeLists.txt
  CMakePresets.json
  HDF4Examples/.gitignore
  HDF4Examples/C/AN/CMakeLists.txt
  HDF4Examples/C/GR/CMakeLists.txt
  HDF4Examples/C/GR/h4ex_GR_create_and_write_chunked_image.c
  HDF4Examples/C/SD/CMakeLists.txt
  HDF4Examples/C/VD/CMakeLists.txt
  HDF4Examples/C/VG/CMakeLists.txt
  HDF4Examples/CMakeUserPresets.json
  HDF4Examples/FORTRAN/SD/CMakeLists.txt
  HDF4Examples/config/cmake-presets/hidden-presets.json
  config/cmake/HDF4ExampleCache.cmake
  config/cmake/patch.xml
  hdf/fortran/CMakeLists.txt
  hdf/fortran/CMakeTests.cmake
  hdf/src/CMakeLists.txt
  hdf/test/CMakeLists.txt
  hdf/util/CMakeLists.txt
  mfhdf/dumper/CMakeLists.txt
  mfhdf/fortran/CMakeLists.txt
  mfhdf/fortran/CMakeTests.cmake
  mfhdf/hdfimport/CMakeLists.txt
  mfhdf/hdfimport/CMakeTests.cmake
  mfhdf/hdiff/CMakeLists.txt
  mfhdf/hdiff/CMakeTests.cmake
  mfhdf/hrepack/CMakeLists.txt
  mfhdf/hrepack/CMakeTests.cmake
  mfhdf/libsrc/CMakeLists.txt
  mfhdf/ncdump/CMakeLists.txt
  mfhdf/ncgen/CMakeLists.txt
  mfhdf/nctest/CMakeLists.txt
  mfhdf/test/CMakeLists.txt
  mfhdf/test/CMakeTests.cmake
  mfhdf/xdr/CMakeLists.txt
Labels: Component - Build, Component - Misc, Component - Testing, Type - Bug, Type - Improvement, Type - New Feature, Priority - 0. Blocker ⛔

#486 Update README.md with new release info
  README.md
Labels: Component - Misc, Type - Task, Priority - 3. Low 🔽

#485 Remove experimental caching
  hdf/src/hfile.c
  hdf/src/hproto.h
  hdf/test/tvset.c
  release_notes/misc_docs.txt
Labels: Component - C Library, Type - Deprecation / Removal, Priority - 3. Low 🔽

#492 Fix all maybe-uninitialized warnings
  hdf/util/he_main.c
  mfhdf/dumper/hdp_list.c
  mfhdf/hdfimport/hdfimport.c
  mfhdf/test/tcoordvar.c
Labels: Component - C Library, Component - Tools, Type - Improvement, Priority - 2. Medium ⏹

#491 Minor normalization of configure.ac w/ HDF5
  configure.ac
Labels: Component - Build, Type - Improvement, Priority - 3. Low 🔽

#484 Cleaned up ifdefs in mfhdf
  mfhdf/fortran/jackets.c.in
  mfhdf/fortran/mfsdf.c
  mfhdf/libsrc/array.c
  mfhdf/libsrc/attr.c
  mfhdf/libsrc/cdf.c
  mfhdf/libsrc/dim.c
  mfhdf/libsrc/file.c
  mfhdf/libsrc/hdfsds.c
  mfhdf/libsrc/local_nc.h
  mfhdf/libsrc/mfdatainfo.c
  mfhdf/libsrc/mfhdf.h
  mfhdf/libsrc/mfsd.c
  mfhdf/libsrc/nssdc.c
  mfhdf/libsrc/putget.c
  mfhdf/libsrc/putgetg.c
  mfhdf/libsrc/sharray.c
  mfhdf/libsrc/string.c
  mfhdf/libsrc/var.c
  mfhdf/ncdump/ncdump.c
  mfhdf/nctest/add.c
  mfhdf/nctest/atttests.c
  mfhdf/nctest/cdftests.c
  mfhdf/nctest/dimtests.c
  mfhdf/nctest/error.h
  mfhdf/nctest/rec.c
  mfhdf/nctest/slabs.c
  mfhdf/nctest/testcdf.h
  mfhdf/nctest/vardef.c
  mfhdf/nctest/varget.c
  mfhdf/nctest/varget_unlim.c
  mfhdf/nctest/vargetg.c
  mfhdf/nctest/varput.c
  mfhdf/nctest/varputg.c
  mfhdf/nctest/vartests.c
  mfhdf/nctest/vputget.c
  mfhdf/nctest/vputgetg.c
  mfhdf/test/cdftest.c
  mfhdf/test/gen_sds_szipped.c
  mfhdf/test/hdftest.c
  mfhdf/test/tattributes.c
  mfhdf/test/tchunk.c
  mfhdf/test/tcomp.c
  mfhdf/test/tcoordvar.c
  mfhdf/test/tdatasizes.c
  mfhdf/test/tdim.c
  mfhdf/test/temptySDSs.c
  mfhdf/test/texternal.c
  mfhdf/test/tfile.c
  mfhdf/test/tmixed_apis.c
  mfhdf/test/tnetcdf.c
  mfhdf/test/trank0.c
  mfhdf/test/tsd.c
  mfhdf/test/tsdsprops.c
  mfhdf/test/tutils.c
Labels: Component - C Library, Component - Fortran, Component - Tools, Component - netCDF, Type - Deprecation / Removal, Priority - 3. Low 🔽

#476 Fix incorrect option mask returned by SDgetcompinfo
  hdf/src/cszip.c
  hdf/src/hchunks.c
  hdf/src/hproto.h
  hdf/src/mfgr.c
  hdf/test/tszip.c
  mfhdf/dumper/testfiles/dumpsds-15.out
  mfhdf/dumper/testfiles/dumpsds-15szip.out
  mfhdf/libsrc/mfsd.c
  mfhdf/test/tszip.c
Labels: Component - C Library, Type - Bug, Priority - 2. Medium ⏹

#493 Fix bintest by using platform specific workflows
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-ctest.yml
  CMakePresets.json
Labels: Component - Build, Component - Misc, Type - Bug, Priority - 0. Blocker ⛔

#494 Set HDF4 version to 4.3.0-1
  README.md
  config/cmake/scripts/HDF4config.cmake
  hdf/src/hfile.h
  java/src/hdf/hdflib/HDFLibrary.java
  java/test/TestH4.java
  release_notes/RELEASE.txt
Labels: Component - Build, Type - Task, Priority - 0. Blocker ⛔

#498 Fix a warning from unused error handling
  hdf/src/cszip.c
Labels: Component - C Library, Type - Improvement, Priority - 2. Medium ⏹

#499 Remove HDF5 things from .clang-format
  .clang-format
Labels: Component - Misc, Type - Improvement, Priority - 3. Low 🔽

#500 Fix NULL dereference warnings in dfimcomp.c
  hdf/src/dfimcomp.c
Labels: Component - C Library, Type - Improvement, Priority - 2. Medium ⏹

#502 Fix shadowed variable in hdfls.c
  hdf/util/hdfls.c
Labels: Component - Tools, Type - Improvement, Priority - 2. Medium ⏹

#504 Fix warnings in testhdf
  hdf/test/testhdf.c
Labels: Component - Testing, Type - Improvement, Priority - 3. Low 🔽

#503 Fix size warnings in dfimcomp.c
  hdf/src/dfimcomp.c
Labels: Component - C Library, Type - Improvement, Priority - 3. Low 🔽

#506 mfsd.c SDgetcompress: Remove unused variables.
  mfhdf/libsrc/mfsd.c
Labels: Priority - 3. Low 🔽

#508 Fix warnings in hdf/util/he_<foo> code
  hdf/test/rig.c
  hdf/util/he.h
  hdf/util/he_cntrl.c
  hdf/util/he_main.c
Labels: Component - Tools, Type - Improvement, Priority - 3. Low 🔽

#509 Clean up hdiff_vs.c
  mfhdf/hdiff/hdiff_vs.c
Labels: Component - Tools, Type - Improvement, Priority - 3. Low 🔽

#514 Corrected malloc statements
  hdf/test/tvnameclass.c
  hdf/test/tvset.c
Labels: Component - C Library, Type - Bug, Priority - 0. Blocker ⛔

#510 Fixed SZIP availability check
  hdf/src/hcomp.c
  hdf/src/mfgr.c
  mfhdf/dumper/hdp_sds.c
  mfhdf/dumper/testfiles/dumpsds-15.out
Labels: Component - C Library

#512 Cleaned up datainfo header files
  hdf/src/hdatainfo.h
  hdf/src/hproto.h
  mfhdf/libsrc/mfdatainfo.h
  mfhdf/libsrc/mfhdf.h
Labels: Component - C Library, Type - Improvement, Priority - 2. Medium ⏹

#516 Remove unused symbols from hdf2gif.c
  hdf/util/hdf2gif.c
Labels: Component - Tools, Type - Improvement, Priority - 3. Low 🔽

#517 Removes remnants of FNAME scheme
  hdf/src/hdfi.h
  hdf/src/mfanf.c
  hdf/src/vgf.c
  mfhdf/fortran/mfsdf.c
Labels: Component - Fortran, Type - Deprecation / Removal, Priority - 3. Low 🔽

#518 Remove Fortran FRETVAL macros
  hdf/src/df24f.c
  hdf/src/dfanf.c
  hdf/src/dff.c
  hdf/src/dfpf.c
  hdf/src/dfr8f.c
  hdf/src/dfsdf.c
  hdf/src/dfufp2if.c
  hdf/src/dfutilf.c
  hdf/src/hdfi.h
  hdf/src/herrf.c
  hdf/src/hfilef.c
  hdf/src/hproto_fortran.h
  hdf/src/mfanf.c
  hdf/src/mfgrf.c
  hdf/src/vattrf.c
  hdf/src/vgf.c
  hdf/test/forsupf.c
  hdf/test/fortest.h
  mfhdf/fortran/mfsdf.c
  mfhdf/fortran/mfsdf.h
Labels: Component - Fortran, Type - Deprecation / Removal, Priority - 3. Low 🔽

#520 Moves some things from hdfi.h to hdf.h
  hdf/src/hdf.h
  hdf/src/hdfi.h
  hdf/src/tbbt.h
Labels: Component - C Library, Type - Improvement, Priority - 1. High 🔼

#522 Update and add INSTALL files and versions in docs
  HDF4Examples/Using_CMake.txt
  README.md
  config/cmake/scripts/HDF4config.cmake
  release_notes/INSTALL
  release_notes/INSTALL_Auto.txt
  release_notes/INSTALL_CMake.txt
  release_notes/INSTALL_WINDOWS.txt
  release_notes/USING_CMake_Examples.txt
  release_notes/USING_HDF4_CMake.txt
  release_notes/USING_HDF4_VS.txt
Labels: Component - Documentation, Type - Improvement, Priority - 2. Medium ⏹

#515 Add ABI compatibility reports
  .github/workflows/abi-report.yml
  .github/workflows/clang-format-check.yml
  .github/workflows/codespell.yml
  .github/workflows/daily-build.yml
  .github/workflows/intel-auto.yml
  .github/workflows/intel-cmake.yml
  .github/workflows/main-cmake.yml
  .github/workflows/release-files.yml
  .github/workflows/release.yml
  .github/workflows/tarball.yml
Labels: Component - Misc, Type - Improvement, Priority - 1. High 🔼

#523 Standardize on ON/OFF for boolean CMake options
  HDF4Examples/config/cmake/HDFMacros.cmake
  config/cmake/HDF4ExampleCache.cmake
  config/cmake/HDFMacros.cmake
Labels: Component - Documentation, Type - Improvement, Priority - 3. Low 🔽

#524 Remove unused Duff's device ifdefs
  hdf/src/dfkswap.c
  hdf/src/hconv.h
Labels: Component - C Library, Type - Improvement, Priority - 3. Low 🔽

#525 Remove DFconvert() macro
  hdf/src/dfconvrt.h
  hdf/src/dfsd.c
Labels: Component - C Library, Type - Deprecation / Removal, Priority - 3. Low 🔽

#526 Fix size warnings in hdiff
  mfhdf/hdiff/hdiff_vs.c
Labels: Component - Tools, Type - Improvement, Priority - 3. Low 🔽

#527 Fix a too-small buffer issue in hdp
  mfhdf/dumper/hdp_sds.c
Labels: Component - Tools, Type - Improvement, Priority - 1. High 🔼

#528 Remove codeql for now
  .github/workflows/codeql.yml
Labels: Component - Testing, Type - Deprecation / Removal, Priority - 3. Low 🔽

#529 Remove dead code from testcdf.h
  mfhdf/nctest/testcdf.h
Labels: Component - netCDF, Component - Testing, Type - Deprecation / Removal, Priority - 3. Low 🔽

#530 Remove the VSET_INTERFACE macro
  hdf/src/vattr.c
  hdf/src/vattrf.c
  hdf/src/vconv.c
  hdf/src/vg.c
  hdf/src/vg.h
  hdf/src/vgf.c
  hdf/src/vgp.c
  hdf/src/vhi.c
  hdf/src/vio.c
  hdf/src/vparse.c
  hdf/src/vrw.c
  hdf/src/vsfld.c
  hdf/util/vshow.c
  mfhdf/dumper/hdp.c
  mfhdf/dumper/show.c
Labels: Component - C Library, Component - Tools, Type - Deprecation / Removal, Priority - 3. Low 🔽

#531 Remove TBBT_INTERNALS scheme
  hdf/src/hdatainfo.c
  hdf/src/mfan.c
  hdf/src/mfgr.c
  hdf/src/tbbt.c
  hdf/src/tbbt.h
  hdf/src/vgp.c
  hdf/src/vio.c
Labels: Component - C Library, Type - Improvement, Priority - 3. Low 🔽

#532 Fix all warnings about shadowed variables
  hdf/util/hdfgifwr.c
  hdf/util/hdfpack.c
  hdf/util/vshow.c
  mfhdf/hdfimport/hdfimport.c
  mfhdf/nctest/add.c
  mfhdf/nctest/atttests.c
  mfhdf/nctest/cdftests.c
  mfhdf/nctest/dimtests.c
  mfhdf/nctest/driver.c
  mfhdf/nctest/slabs.c
  mfhdf/nctest/testcdf.h
  mfhdf/nctest/vardef.c
  mfhdf/nctest/varget.c
  mfhdf/nctest/vargetg.c
  mfhdf/nctest/varput.c
  mfhdf/nctest/varputg.c
  mfhdf/nctest/vartests.c
  mfhdf/nctest/vputget.c
  mfhdf/nctest/vputgetg.c
Labels: Component - Tools, Component - netCDF, Component - Testing, Type - Improvement, Priority - 2. Medium ⏹

#533 Fix jpeg test const issue
  hdf/test/rig.c
  hdf/test/tusejpegfuncs.c
Labels: Component - Testing, Type - Improvement, Priority - 2. Medium ⏹

#534 Fix maybe-uninitialized warnings in hfile.c
  hdf/src/hfile.c
Labels: Component - C Library, Type - Improvement, Priority - 2. Medium ⏹

#536 Fix size warnings in hdf/test/bitio.c
  hdf/test/bitio.c
Labels: Component - Testing, Type - Improvement, Priority - 3. Low 🔽

#535 Add MSYS2 actions to CI using CMake
  .github/workflows/main.yml
  .github/workflows/msys2-cmake.yml
Labels: Component - Build, Component - Misc, Component - Testing, Type - New Feature, Priority - 1. High 🔼

#256 Adds CHECK macros to test_file_limits (tfile1.c)
  hdf/test/file1.c
Labels: Component - Testing, WIP, Type - Bug, Priority - 0. Blocker ⛔

#537 Fix several stack/frame size warnings
  hdf/test/blocks.c
  hdf/test/chunks.c
  hdf/test/extelt.c
  hdf/test/file.c
  mfhdf/test/hdftest.c
Labels: Component - Testing, Type - Improvement, Priority - 3. Low 🔽

#538 Delete old snapshot binaries after new snapshots are created
  .github/workflows/daily-build.yml
  .github/workflows/hdfeos2.yml
  .github/workflows/main-auto.yml
  .github/workflows/main-cmake-mingw.yml
  .github/workflows/main-cmake.yml
  .github/workflows/ppc64.yml
  .github/workflows/remove-files.yml
Labels: Component - Misc, Component - Testing, Type - New Feature, Priority - 0. Blocker ⛔

#539 Correct String FIND for runTest and grepTest
  CMakeLists.txt
  CMakePresets.json
  HDF4Examples/config/cmake/grepTest.cmake
  HDF4Examples/config/cmake/runTest.cmake
  config/cmake-presets/hidden-presets.json
  config/cmake/grepTest.cmake
  config/cmake/runTest.cmake
  hdf/src/CMakeLists.txt
Labels: Component - Testing, Type - Bug, Priority - 0. Blocker ⛔

#540 Move XDR license info to COPYING
  COPYING
  mfhdf/libsrc/xdr_NOTICE.h
  mfhdf/libsrc/xdr_README
Labels: Component - Documentation, Type - Improvement, Priority - 0. Blocker ⛔

#541 Ensure that java requires shared in Autotools
  configure.ac
Labels: Component - Build, Component - Java, Type - Bug, Priority - 1. High 🔼

#543 Lower BIG value in hdf/test/file1.c
  hdf/test/file1.c
Labels: Component - Testing, Type - Improvement, Priority - 1. High 🔼

#548 Fix encoder detection w/ --with-szlib & no paths
  configure.ac
  mfhdf/test/tszip.c
  release_notes/RELEASE.txt
Labels: Component - Build, Component - Tools, Component - Testing, Type - Bug, Priority - 0. Blocker ⛔

#542 Fix clang warnings
  hdf/src/dfsd.c
  hdf/src/dfunjpeg.c
  hdf/test/mgr.c
  hdf/util/gif2hdf.c
  mfhdf/hdfimport/hdfimport.c
  mfhdf/libsrc/putget.c
  mfhdf/test/tncvargetfill.c
Labels: Component - C Library, Component - Tools, Component - Testing, Type - Improvement, Priority - 3. Low 🔽

#545 Remove extraneous void casts
  hdf/src/mcache.c
  hdf/src/vgf.c
  hdf/test/forsupf.c
  hdf/util/fp2hdf.c
  hdf/util/fptest.c
  hdf/util/he_disp.c
  mfhdf/fortran/mfsdf.c
  mfhdf/hdfimport/hdfimporttest.c
  mfhdf/hdiff/hdiff.h
  mfhdf/hdiff/hdiff_main.c
  mfhdf/hdiff/hdiff_misc.c
  mfhdf/libsrc/string.c
  mfhdf/ncdump/dumplib.c
  mfhdf/ncdump/ncdump.c
  mfhdf/ncdump/ncdump.h
  mfhdf/ncdump/vardata.c
  mfhdf/ncgen/close.c
  mfhdf/ncgen/generate.c
  mfhdf/ncgen/genlib.c
  mfhdf/ncgen/load.c
  mfhdf/nctest/add.c
  mfhdf/nctest/atttests.c
  mfhdf/nctest/cdftests.c
  mfhdf/nctest/dimtests.c
  mfhdf/nctest/error.c
  mfhdf/nctest/misctest.c
  mfhdf/nctest/rec.c
  mfhdf/nctest/val.c
  mfhdf/nctest/vardef.c
  mfhdf/nctest/varget.c
  mfhdf/nctest/varget_unlim.c
  mfhdf/nctest/vargetg.c
  mfhdf/nctest/varput.c
  mfhdf/nctest/varputg.c
  mfhdf/nctest/vartests.c
  mfhdf/nctest/vputget.c
  mfhdf/nctest/vputgetg.c
  mfhdf/test/cdftest.c
  mfhdf/util/h4getopt.c
Labels: Component - C Library, Component - Fortran, Component - Tools, Component - netCDF, Component - Testing, Type - Improvement, Priority - 2. Medium ⏹

#550 Checked for invalid file ID
  hdf/src/hfile.c
  hdf/src/vgp.c
Labels: Component - C Library, Type - Bug, Priority - 1. High 🔼

#546 Use AC_MSG macros in configure.ac
  configure.ac
Labels: Component - Build, Type - Improvement, Priority - 3. Low 🔽

#553 Load missing gcc general warnings in Autotools
  config/gnu-flags
Labels: Component - Build, Type - Bug, Priority - 1. High 🔼

#554 Remove unused done target from an szip function
  hdf/src/mfgr.c
Labels: Component - C Library, Type - Improvement, Priority - 3. Low 🔽

#544 Sync Autotools m4 Java files w/ HDF5
  m4/ax_check_class.m4
  m4/ax_check_classpath.m4
  m4/ax_check_java_home.m4
  m4/ax_check_junit.m4
  m4/ax_check_rqrd_class.m4
  m4/ax_java_check_class.m4
  m4/ax_java_options.m4
  m4/ax_jni_include_dir.m4
  m4/ax_prog_jar.m4
  m4/ax_prog_java.m4
  m4/ax_prog_java_cc.m4
  m4/ax_prog_java_works.m4
  m4/ax_prog_javac.m4
  m4/ax_prog_javac_works.m4
  m4/ax_prog_javadoc.m4
  m4/ax_prog_javah.m4
  m4/ax_try_compile_java.m4
  m4/ax_try_run_java.m4
Labels: Component - Build, Component - Java, Type - Improvement, Priority - 3. Low 🔽

#551 Fix srcdir issues
  configure.ac
  hdf/test/CMakeLists.txt
  hdf/test/bitio.c
  hdf/test/litend.c
  hdf/test/mgr.c
  hdf/test/srcdir_str.h.in
  hdf/test/tutils.c
  hdf/test/tutils.h
  hdf/test/tvnameclass.c
  mfhdf/test/CMakeLists.txt
  mfhdf/test/hdftest.h
  mfhdf/test/srcdir_str.h.in
  mfhdf/test/tfile.c
  mfhdf/test/tnetcdf.c
  mfhdf/test/tszip.c
  mfhdf/test/tutils.c
Labels: Component - Testing, Type - Improvement, Priority - 1. High 🔼

#556 Update download url to fix broken link
  README.md
Labels: Component - Documentation, Type - Bug, Priority - 0. Blocker ⛔

#555 Update Autotools clang flags
  config/clang-flags
Labels: Component - Build, Type - Improvement, Priority - 1. High 🔼

#558 Fix a potential uninitialized value in test/litend.c
  hdf/test/litend.c
Labels: Component - Testing, Type - Improvement, Priority - 2. Medium ⏹

#559 Remove unused make_datafilename() function
  mfhdf/test/hdftest.h
  mfhdf/test/texternal.c
  mfhdf/test/tutils.c
Labels: Component - Testing, Type - Deprecation / Removal, Priority - 2. Medium ⏹

#561 Correct preset for fortran
  CMakePresets.json
Labels: Component - Build, Component - Testing, Priority - 0. Blocker ⛔

#564 remove win-Intel workaround presets
  .github/workflows/cmake-ctest.yml
  CMakePresets.json
  HDF4Examples/CMakePresets.json
Labels: Component - Build, Component - Misc, Component - Testing, Type - Bug, Priority - 0. Blocker ⛔

#566 Add a netCDF action to GitHub CI
  .github/workflows/netcdf.yml
Labels: Component - Testing, Type - Improvement, Priority - 1. High 🔼

#562 Add nvhpc workflow
  .github/workflows/autotools.yml
  .github/workflows/cmake.yml
  .github/workflows/intel-cmake.yml
  .github/workflows/nvhpc-auto.yml
  .github/workflows/nvhpc-cmake.yml
Labels: Component - Misc, Component - Testing, Type - Improvement, Type - New Feature, Priority - 1. High 🔼

#567 Fix for compiling the buffer test
  hdf/test/buffer.c
Labels: Component - Testing, Type - Bug, Priority - 0. Blocker ⛔

#568 No longer deploy private header files
  hdf/src/CMakeLists.txt
  hdf/src/Makefile.am
  mfhdf/libsrc/CMakeLists.txt
  mfhdf/libsrc/Makefile.am
  release_notes/RELEASE.txt
Labels: Component - Build, Type - Deprecation / Removal, Priority - 0. Blocker ⛔

#569 Update README.md with new URL for generic HDF4 info
  README.md
Labels: Type - Improvement, Priority - 3. Low 🔽

#565 Add options to allow tools type selection and naming
  CMakeLists.txt
  HDF4Examples/config/cmake/HDFExampleMacros.cmake
  config/cmake/HDF4ExampleCache.cmake
  config/cmake/hdf4-config.cmake.in
  hdf/fortran/CMakeLists.txt
  hdf/src/CMakeLists.txt
  hdf/util/CMakeLists.txt
  hdf/util/CMakeTests.cmake
  mfhdf/dumper/CMakeLists.txt
  mfhdf/dumper/CMakeTests.cmake
  mfhdf/fortran/CMakeLists.txt
  mfhdf/hdfimport/CMakeLists.txt
  mfhdf/hdfimport/CMakeTests.cmake
  mfhdf/hdiff/CMakeLists.txt
  mfhdf/hdiff/CMakeTests.cmake
  mfhdf/hrepack/CMakeLists.txt
  mfhdf/hrepack/CMakeTests.cmake
  mfhdf/libsrc/CMakeLists.txt
  mfhdf/ncdump/CMakeLists.txt
  mfhdf/ncdump/CMakeTests.cmake
  mfhdf/ncgen/CMakeLists.txt
  mfhdf/ncgen/CMakeTests.cmake
  release_notes/INSTALL_CMake.txt
  release_notes/RELEASE.txt
Labels: Component - Build, Component - Tools, Component - Testing, Type - Improvement, Priority - 1. High 🔼

#571 Error early on CMake when Java is built w/o shared
  CMakeLists.txt
Labels: Component - Build, Component - Java, Type - Improvement, Priority - 1. High 🔼

#572 Moves internal error macros to herr_priv.h
  hdf/src/CMakeLists.txt
  hdf/src/hdfi.h
  hdf/src/herr.h
  hdf/src/herr_priv.h
Labels: Component - C Library, Type - Deprecation / Removal, Priority - 0. Blocker ⛔

#574 Remove ncgen strtol hack
  mfhdf/ncgen/ncgen.l
  mfhdf/ncgen/ncgenyy.c
Labels: Component - C Library, Component - netCDF, Type - Improvement, Priority - 3. Low 🔽

#578 Add aocc workflows
  .github/workflows/aocc-auto.yml
  .github/workflows/aocc-cmake.yml
  .github/workflows/autotools.yml
  .github/workflows/cmake.yml
Labels: Component - Misc, Component - Testing, Type - Improvement, Type - New Feature, Priority - 2. Medium ⏹

#575 Fix typo stolen^Wborrowed.
  configure.ac
Labels: Component - Build, Type - Improvement, Priority - 3. Low 🔽

#581 Remove unused macros from mfsd/datainfo.c
  mfhdf/libsrc/mfdatainfo.c
  mfhdf/libsrc/mfsd.c
Labels: Component - C Library, Type - Deprecation / Removal, Priority - 3. Low 🔽

#582 Make some hbitio.h things private
  hdf/src/CMakeLists.txt
  hdf/src/hbitio.c
  hdf/src/hbitio.h
  hdf/src/hbitio_priv.h
  hdf/src/hdf.h
  release_notes/RELEASE.txt
Labels: Component - C Library, Type - Deprecation / Removal, Priority - 0. Blocker ⛔

#585 Restore df.h to the list of public headers
  hdf/src/CMakeLists.txt
  hdf/src/Makefile.am
  hdf/src/df.h
  hdf/src/dfanf.c
  hdf/src/dff.c
  hdf/src/dfstubs.c
  hdf/src/hproto_fortran.h
  release_notes/RELEASE.txt
Labels: Component - C Library, Type - Improvement, Priority - 0. Blocker ⛔

#584 Add netCDF license to COPYING
  COPYING
Labels: Component - Misc, Type - Improvement, Priority - 1. High 🔼

#586 Add a 4.2 --> 4.3 migration guide
  doc/HDF-4.2-to-4.3-migration.md
Labels: Component - Documentation, Type - Improvement, Priority - 0. Blocker ⛔

#583 Move version symbols to hfile.h
  CMakeLists.txt
  bin/h4vers
  hdf/src/CMakeLists.txt
  hdf/src/Makefile.am
  hdf/src/hfile.h
  hdf/src/hfile_priv.h
  release_notes/RELEASE.txt
Labels: Component - C Library, Type - Improvement, Priority - 0. Blocker ⛔

#587 Add deb and rpm binaries to snapshots
  .github/workflows/cmake-ctest.yml
  .github/workflows/release-files.yml
  .github/workflows/remove-files.yml
  config/cmake-presets/hidden-presets.json
Labels: Component - Build, Component - Misc, Type - Improvement, Type - New Feature, Priority - 2. Medium ⏹

#589 Fix all broken links in config/sanitizer/README.md.
  config/sanitizer/README.md
Labels: Component - Documentation, Type - Deprecation / Removal, Priority - 1. High 🔼

#590 Updated the release check script
  bin/h4_release_check.sh
Labels: Component - Testing, Type - Improvement, Priority - 1. High 🔼

#593 Support OpenBSD for Autotools.
  configure.ac
Labels: Component - Build, Type - Improvement, Priority - 1. High 🔼

#594 Fix undefined operations in atom code
  hdf/src/atom.c
Labels: Component - C Library, Type - Improvement, Priority - 2. Medium ⏹

#591 Fix memory leak in ncdump
  mfhdf/ncdump/ncdump.c
Labels: Component - Tools, Component - netCDF, Type - Improvement, Priority - 2. Medium ⏹

#592 Fix memory leaks in nctest
  mfhdf/nctest/driver.c
Labels: Component - netCDF, Component - Testing, Type - Improvement, Priority - 1. High 🔼

#595 Order sys headers as per MSDN
  hdf/src/hdf_priv.h
Labels: Component - C Library, Type - Improvement, Priority - 1. High 🔼

#596 Remove unused variable warning
  hdf/src/mcache.c
Labels: Component - Build, Type - Deprecation / Removal, Priority - 2. Medium ⏹

#597 Update cmake tools from original site
  config/sanitizer/README.md
  config/sanitizer/code-coverage.cmake
  config/sanitizer/formatting.cmake
  config/sanitizer/sanitizers.cmake
  config/sanitizer/tools.cmake
Labels: Component - Misc, Component - Testing, Type - Improvement, Priority - 2. Medium ⏹

#600 Add a netCDF GitHub shield
  README.md
Labels: Component - Documentation, Component - Testing, Type - Improvement, Priority - 2. Medium ⏹

#599 Minor changes to comments/docs
  doc/HDF-4.2-to-4.3-migration.md
  hdf/src/df.h
Labels: Component - C Library, Component - Documentation, Type - Improvement, Priority - 1. High 🔼

#598 Remove unneeded tools
  config/sanitizer/README.md
Labels: Component - Documentation, Type - Deprecation / Removal, Priority - 0. Blocker ⛔

#603 Corrected handling of SDgetcompress()
  config/cmake/h4config.h.in
  config/cmake/libhdf4.settings.cmake.in
  java/src/jni/hdfsdsImp.c
  java/src/jni/hdfsdsImp.h
  libhdf4.settings.in
  mfhdf/libsrc/mfhdf.h
  mfhdf/test/tcomp.c
  release_notes/RELEASE.txt
Labels: Component - Build, Component - C Library, Component - Java, Type - Bug, Type - Improvement, Priority - 1. High 🔼

#609 Tidy DFR8-related code
  hdf/src/dfr8.c
  hdf/src/hfile.c
  hdf/test/tdatainfo.c
  hdf/test/tdfr8.c
  hdf/util/r8tohdf.c
Labels: Component - C Library, Component - Tools, Component - Testing, Type - Improvement, Priority - 3. Low 🔽

#602 Normalization of CMake and Autotools
  config/cmake/ConfigureChecks.cmake
  config/cmake/GetTimeOfDayTest.cpp
  config/cmake/HDFTests.c
  config/cmake/h4config.h.in
  configure.ac
  release_notes/RELEASE.txt
Labels: Component - Build, Type - Deprecation / Removal, Type - Improvement, Priority - 1. High 🔼

#607 Consolidate cygwin Autotools files
  config/cygwin
  config/i686-pc-cygwin
  config/x86_64-pc-cygwin
Labels: Component - Build, Type - Improvement, Priority - 2. Medium ⏹

#606 Remove config/powerpc-apple
  config/powerpc-apple
Labels: Component - Build, Type - Deprecation / Removal, Priority - 2. Medium ⏹

#605 Fix most float-equal warnings
  hdf/test/chunks.c
  hdf/test/mgr.c
  hdf/test/sdmms.c
  hdf/test/sdnmms.c
  hdf/test/slab.c
  hdf/test/tutils.h
  hdf/test/tvset.c
  mfhdf/nctest/slabs.c
  mfhdf/nctest/testcdf.h
  mfhdf/nctest/val.c
  mfhdf/nctest/varget_unlim.c
  mfhdf/nctest/vartests.c
  mfhdf/test/hdftest.c
  mfhdf/test/hdftest.h
  mfhdf/test/tchunk.c
  mfhdf/test/tcoordvar.c
  mfhdf/test/temptySDSs.c
  mfhdf/test/tszip.c
Labels: Component - Testing, Type - Improvement, Priority - 2. Medium ⏹

#610 Address comments in HCget_config_info()
  hdf/src/cnone.c
  hdf/src/hcomp.c
Labels: Component - C Library, Type - Improvement, Priority - 2. Medium ⏹

#611 Cleanup CMake code
  CMakeLists.txt
  HDF4Examples/config/cmake/HDFMacros.cmake
  config/cmake/HDFMacros.cmake
  config/cmake/mccacheinit.cmake
  hdf/src/CMakeLists.txt
  hdf/util/CMakeTests.cmake
  hdf/util/writehdf.c
  mfhdf/dumper/CMakeTests.cmake
  mfhdf/hdfimport/CMakeTests.cmake
  mfhdf/hdiff/CMakeTests.cmake
  mfhdf/hrepack/CMakeTests.cmake
  mfhdf/ncdump/CMakeTests.cmake
  mfhdf/ncgen/CMakeTests.cmake
  release_notes/INSTALL_CMake.txt
Labels: Component - Build, Type - Improvement, Priority - 0. Blocker ⛔

#613 Fix warnings in compression code
  hdf/src/atom.c
  hdf/src/atom_priv.h
  hdf/src/cdeflate.c
  hdf/src/cdeflate_priv.h
  hdf/src/cnbit.c
  hdf/src/cnbit_priv.h
  hdf/src/crle.c
  hdf/src/crle_priv.h
  hdf/src/cszip.c
  hdf/src/cszip_priv.h
  hdf/src/hcomp.c
Labels: Component - C Library, Type - Improvement, Priority - 3. Low 🔽

#615 Revert mfhdf/nctest/slabs.c file
  mfhdf/nctest/slabs.c
Labels: Component - netCDF, Component - Testing, Type - Bug, Priority - 0. Blocker ⛔

#617 Fix a 4-byte swap that uses weird code
  hdf/src/dfkswap.c
Labels: Component - C Library, Type - Improvement, Priority - 3. Low 🔽

#618 Fix const warning in nctest
  mfhdf/nctest/atttests.c
  mfhdf/nctest/tests.h
Labels: Component - netCDF, Component - Testing, Type - Improvement, Priority - 3. Low 🔽

#619 Remove dead code from nctest stabs.c
  mfhdf/nctest/slabs.c
Labels: Component - netCDF, Component - Testing, Type - Deprecation / Removal, Priority - 3. Low 🔽

#620 Add soversion to libraries for CMake
  CMakeInstallation.cmake
  CMakeLists.txt
  config/cmake/HDF4Macros.cmake
  config/cmake/JPEG/CMakeLists.txt
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/ZLIB/CMakeLists.txt
  config/lt_vers.am
  hdf/fortran/CMakeLists.txt
  hdf/fortran/CMakeTests.cmake
  hdf/src/CMakeLists.txt
  java/src/jni/CMakeLists.txt
  mfhdf/fortran/CMakeLists.txt
  mfhdf/libsrc/CMakeLists.txt
Labels: Component - Build, Component - C Library, Type - Improvement, Type - New Feature, Priority - 0. Blocker ⛔

#624 Update config with nvhpc compile flags
  config/clang-flags
  config/cmake/HDF4UseFortran.cmake
  config/cmake/HDFCompilerFlags.cmake
  config/gnu-flags
  config/gnu-warnings/general
  config/linux-gnu
  config/nvidia-flags
  config/oneapi-flags
Labels: Component - Build, Component - C Library, Type - Improvement, Priority - 0. Blocker ⛔

#626 Remove zlib and jpeg as options, update INSTALL file
  CMakeFilters.cmake
  CMakeLists.txt
  CMakePresets.json
  release_notes/INSTALL_CMake.txt
Labels: Component - Build, Component - Documentation, Type - Deprecation / Removal, Priority - 0. Blocker ⛔

#630 Fix for big-endian systems
  hdf/src/hdf_priv.h
Labels: Component - C Library, Type - Bug, Priority - 0. Blocker ⛔

#631 Use >= in verbose macro
  hdf/test/tutils.h
Labels: Component - Testing, Type - Improvement, Priority - 2. Medium ⏹

#632 Fix build mode in Autotools GH actions
  .github/workflows/aocc-auto.yml
  .github/workflows/autotools.yml
  .github/workflows/intel-auto.yml
  .github/workflows/main-auto.yml
  .github/workflows/nvhpc-auto.yml
  .github/workflows/ppc64.yml
Labels: Component - Testing, Type - Bug, Priority - 0. Blocker ⛔

#633 Correct repo name in URLs
  release_notes/INSTALL_CMake.txt
  release_notes/USING_HDF4_CMake.txt
Labels: Component - Documentation, Type - Bug, Priority - 0. Blocker ⛔

#638 Remove limitations on preset generators
  HDF4Examples/config/cmake-presets/hidden-presets.json
  config/cmake-presets/hidden-presets.json
Labels: Component - Build, Component - Misc, Type - Bug, Priority - 0. Blocker ⛔

#640 Removed the INSTALL_CYGWIN.txt file
  release_notes/INSTALL_CYGWIN.txt
Labels: Component - Documentation, Type - Deprecation / Removal, Priority - 2. Medium ⏹

#639 Master install file
  release_notes/USING_HDF4_VS.txt
Labels: Component - Documentation, Type - Bug, Priority - 0. Blocker ⛔

#634 Update platforms Tested
  bin/h4vers
  release_notes/RELEASE.txt
Labels: Component - Documentation, Type - Improvement, Priority - 0. Blocker ⛔

#642 Regenerate ncgen from genparser
  mfhdf/ncgen/ncgenyy.c
Labels: Component - Tools, Component - netCDF, Type - Task, Priority - 2. Medium ⏹

#643 Regenerate ncgen from genparser (#642)
  .github/workflows/codespell.yml
  mfhdf/ncgen/ncgenyy.c
Labels: Component - Misc, Type - Task, Priority - 1. High 🔼

#645 Add NEWSLETTER files
  release_notes/NEWSLETTER.txt
  release_notes/NEWSLETTER_README.txt
Labels: Component - Documentation, Type - Improvement, Priority - 1. High 🔼

#647 Update migration guide with removed functions
  doc/HDF-4.2-to-4.3-migration.md
Labels: Component - Documentation, Type - Improvement, Priority - 1. High 🔼
