Repository HDFGroup/hdf4, pull requests merged in 2024-10, with the labels that each got.

#769 add cdash reporting and fix mac bin test
  .github/workflows/cmake-ctest.yml
  .github/workflows/cmake-script.yml
  .github/workflows/daily-build.yml
  .github/workflows/publish-branch.yml
  .github/workflows/publish-release.yml
  .github/workflows/tarball.yml
  .gitignore
  CMakeFilters.cmake
  HDF4Examples/CMakeLists.txt
  HDF4Examples/CMakePresets.json
  HDF4Examples/FORTRAN/AN/CMakeLists.txt
  HDF4Examples/FORTRAN/GR/CMakeLists.txt
  HDF4Examples/FORTRAN/SD/CMakeLists.txt
  HDF4Examples/FORTRAN/VD/CMakeLists.txt
  HDF4Examples/FORTRAN/VG/CMakeLists.txt
  HDF4Examples/JAVA/exAN/CMakeLists.txt
  HDF4Examples/JAVA/exAN/Java_sourcefiles.cmake
  HDF4Examples/JAVA/exGR/CMakeLists.txt
  HDF4Examples/JAVA/exGR/Java_sourcefiles.cmake
  HDF4Examples/JAVA/exJ/CMakeLists.txt
  HDF4Examples/JAVA/exSD/CMakeLists.txt
  HDF4Examples/JAVA/exSD/Java_sourcefiles.cmake
  HDF4Examples/JAVA/exVD/CMakeLists.txt
  HDF4Examples/JAVA/exVD/Java_sourcefiles.cmake
  HDF4Examples/Using_CMake.txt
  HDF4Examples/config/cmake-presets/hidden-presets.json
  HDF4Examples/config/cmake/HDF4UseFortran.cmake
  HDF4Examples/config/cmake/HDFExampleMacros.cmake
  HDF4Examples/config/cmake/cacheinit.cmake
  bin/warnhist
  config/cmake/HDF4ExampleCache.cmake
  config/cmake/HDFLibMacros.cmake
  config/cmake/examples/CTestScript.cmake
  config/cmake/examples/HDF4_Examples_options.cmake
  config/cmake/scripts/CTestScript.cmake
  config/cmake/scripts/HDF4config.cmake
  config/intel-fflags
  doxygen/Doxyfile.in
  doxygen/dox/rm-template.dox
  release_docs/USING_CMake_Examples.txt
Labels: Component - Build, Component - Testing, Type - Bug, Type - Improvement, Priority - 0. Blocker ⛔

#771 Bump clang-format verion to 17
  .github/workflows/clang-format-check.yml
  .github/workflows/clang-format-fix.yml
  HDF4Examples/C/GR/h4ex_GR_create_and_write_chunked_image.c
  hdf/src/atom.c
  hdf/src/dfgroup.c
  hdf/src/hdf_priv.h
  hdf/src/hfile_priv.h
  hdf/test/mgr.c
  hdf/test/slab.c
  hdf/test/tattdatainfo.c
  hdf/util/gif.h
  hdf/util/hdfgifwr.c
  hdf/util/he_cntrl.c
  hdf/util/he_proto.h
  java/test/TestAll.java
  mfhdf/nctest/varget_unlim.c
  mfhdf/src/array.c
  mfhdf/src/mfsd.c
  mfhdf/test/tmixed_apis.c
  mfhdf/test/tszip.c
Labels: Component - Misc, Type - Task, Priority - 2. Medium ⏹

#774 Fix warnings in t(att)datainfo.c
  mfhdf/test/tattdatainfo.c
  mfhdf/test/tdatainfo.c
Labels: Component - Testing, Type - Improvement, Priority - 3. Low 🔽

#773 Bump nvhpc to 24-7
  .github/workflows/nvhpc-auto.yml
  .github/workflows/nvhpc-cmake.yml
Labels: Component - Testing, Type - Task, Priority - 2. Medium ⏹

#777 Fix warnings when szip isn't present
  hdf/src/cszip.c
  mfhdf/hrepack/hrepack_utils.c
Labels: Component - C Library, Component - Tools, Type - Improvement, Priority - 3. Low 🔽

#775 Fix remaining mfhdf/test warnings
  hdf/src/hfile.c
  hdf/src/hfile_priv.h
  mfhdf/test/cdftest.c
  mfhdf/test/hdftest.h
  mfhdf/test/tattributes.c
  mfhdf/test/tchunk.c
  mfhdf/test/tcomp.c
  mfhdf/test/tdim.c
  mfhdf/test/texternal.c
  mfhdf/test/tfile.c
  mfhdf/test/tmixed_apis.c
  mfhdf/test/tncvargetfill.c
  mfhdf/test/tsdsprops.c
  mfhdf/test/tutils.c
Labels: Component - Testing, Type - Improvement, Priority - 3. Low 🔽

#776 Remove unused test cruft from fortest.c
  hdf/test/fortest.c
Labels: Component - Fortran, Type - Improvement, Priority - 3. Low 🔽

#778 Fix warnings in hdf/test
  hdf/test/chunks.c
  hdf/test/comp.c
  hdf/test/extelt.c
  hdf/test/file.c
  hdf/test/mgr.c
  hdf/test/rig.c
  hdf/test/tattdatainfo.c
  hdf/test/tdatainfo.c
  hdf/test/tvset.c
Labels: Component - Testing, Type - Improvement, Priority - 3. Low 🔽

#779 Remove XDR soversion cruft
  CMakeLists.txt
Labels: Component - Build, Type - Deprecation / Removal, Priority - 3. Low 🔽

#780 Fix size warnings in tbbt.c
  hdf/src/tbbt.c
Labels: Component - C Library, Type - Improvement, Priority - 3. Low 🔽

#782 Add clang cdash report and fix compression compile flags
  .github/workflows/cmake-analysis.yml
  .github/workflows/cmake-script.yml
  .github/workflows/daily-build.yml
  .github/workflows/daily-schedule.yml
  CMakeLists.txt
  config/cmake/JPEG/CMakeLists.txt
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/scripts/HDF4config.cmake
  config/sanitizer/code-coverage.cmake
  hdf/src/CMakeLists.txt
Labels: Component - Build, Component - Misc, Type - Bug, Type - Improvement, Priority - 1. High 🔼

#783 Correct permissions for schedule
  .github/workflows/cmake-analysis.yml
  .github/workflows/daily-schedule.yml
Labels: Component - Misc, Type - Bug, Priority - 0. Blocker ⛔
