Repository HDFGroup/hdf4, pull requests merged in 2024-06, with the labels that each got.

#722 Update workflows to latest versions and merges from hdf5
  .github/workflows/aocc-auto.yml
  .github/workflows/aocc-cmake.yml
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/intel-cmake.yml
  .github/workflows/main-cmake.yml
  .github/workflows/netcdf.yml
  .github/workflows/release-files.yml
  .github/workflows/remove-files.yml
  .github/workflows/tarball.yml
Labels: Component - Misc, Component - Testing, Type - Improvement, Priority - 1. High 🔼

#716 Fix build failure when szip is enabled.
  hdf/src/Makefile.am
  mfhdf/hrepack/Makefile.am
Labels: Component - Build

#724 Add publish to bucket workflow
  .github/workflows/abi-report.yml
  .github/workflows/aocc-auto.yml
  .github/workflows/aocc-cmake.yml
  .github/workflows/autotools.yml
  .github/workflows/cmake-bintest.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/cmake.yml
  .github/workflows/cygwin-auto.yml
  .github/workflows/cygwin-cmake.yml
  .github/workflows/daily-build.yml
  .github/workflows/intel-auto.yml
  .github/workflows/intel-cmake.yml
  .github/workflows/main-auto.yml
  .github/workflows/main-cmake.yml
  .github/workflows/msys2-auto.yml
  .github/workflows/netcdf.yml
  .github/workflows/nvhpc-auto.yml
  .github/workflows/nvhpc-cmake.yml
  .github/workflows/publish-release.yml
  .github/workflows/release-files.yml
  .github/workflows/release.yml
  .github/workflows/remove-files.yml
  .github/workflows/tarball.yml
Labels: Component - Misc, Type - New Feature, Priority - 3. Low 🔽
