Repository HDFGroup/hdf4, pull requests merged in 2024-07, with the labels that each got.

#727 Add 4.4.0 to the release schedule timeline
  doc/img/release-schedule.plantuml
  doc/img/release-schedule.png
Labels: Component - Documentation, Type - Task, Priority - 1. High 🔼

#728 Fix timeline image
  doc/img/release-schedule.plantuml
  doc/img/release-schedule.png
Labels: Component - Documentation, Type - Bug, Priority - 1. High 🔼

#726 Update comp libs and CMake code, also update Java log lib
  .gitattributes
  .github/workflows/cmake-ctest.yml
  .github/workflows/intel-auto.yml
  .github/workflows/main-cmake.yml
  CMakeFilters.cmake
  CMakeInstallation.cmake
  CMakeLists.txt
  CMakePresets.json
  HDF4Examples/CMakePresets.json
  HDF4Examples/JAVA/exJ/Makefile.am
  config/cmake/CPack.Info.plist.in
  config/cmake/ConfigureChecks.cmake
  config/cmake/HDFCompilerFlags.cmake
  config/cmake/HDFLibMacros.cmake
  config/cmake/HDFMacros.cmake
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/LIBAEC/CPack.Info.plist.in
  config/cmake/LIBAEC/config.h.in
  config/cmake/LIBAEC/libaec-config-version.cmake.in
  config/cmake/LIBAEC/libaec-config.cmake.in
  config/cmake/UserMacros/Windows_MT.cmake
  config/cmake/ZLIB/CMakeLists.txt
  config/cmake/ZLIB/zconf.h.in
  config/cmake/ZLIB/zlib-config.cmake.in
  config/cmake/cacheinit.cmake
  config/cmake/grepTest.cmake
  config/cmake/hdf4-config.cmake.in
  config/cmake/runTest.cmake
  config/cmake/scripts/CTestScript.cmake
  config/sanitizer/README.md
  config/sanitizer/code-coverage.cmake
  config/sanitizer/sanitizers.cmake
  config/toolchain/clang.cmake
  java/lib/ext/slf4j-nop-1.7.33.jar
  java/lib/ext/slf4j-nop-2.0.6.jar
  java/lib/ext/slf4j-simple-1.7.33.jar
  java/lib/ext/slf4j-simple-2.0.6.jar
  java/lib/junit.jar
  java/lib/slf4j-api-1.7.33.jar
  java/lib/slf4j-api-2.0.6.jar
  java/src/Makefile.am
  java/src/hdf/overview.html
  java/test/CMakeLists.txt
  java/test/junit.sh.in
  java/test/testfiles/JUnit-TestH4.txt
  java/test/testfiles/JUnit-TestH4ANparams.txt
  java/test/testfiles/JUnit-TestH4DFPparams.txt
  java/test/testfiles/JUnit-TestH4DFRparams.txt
  java/test/testfiles/JUnit-TestH4DFparams.txt
  java/test/testfiles/JUnit-TestH4GRparams.txt
  java/test/testfiles/JUnit-TestH4HCparams.txt
  java/test/testfiles/JUnit-TestH4SDparams.txt
  java/test/testfiles/JUnit-TestH4VSparams.txt
  java/test/testfiles/JUnit-TestH4Vparams.txt
Labels: Component - Build, Component - Misc, Component - Java, Type - Deprecation / Removal, Type - Improvement, Priority - 1. High 🔼

#731 Update CMake with changes in HDF5 - add zlibng option
  CMakeFilters.cmake
  CMakeInstallation.cmake
  HDF4Examples/config/cmake/HDFExampleMacros.cmake
  config/cmake-presets/hidden-presets.json
  config/cmake/LIBAEC/CMakeLists.txt
  config/cmake/ZLIB/CMakeLists.txt
  config/cmake/ZLIBNG/CMakeLists.txt
  config/cmake/ZLIBNG/CPack.Info.plist.in
  config/cmake/ZLIBNG/zconf.h.in
  config/cmake/ZLIBNG/zlib-config-version.cmake.in
  config/cmake/ZLIBNG/zlib-config.cmake.in
  config/cmake/cacheinit.cmake
  config/cmake/hdf4-config.cmake.in
  java/src/hdf/hdflib/HDFLibrary.java
  java/src/jni/CMakeLists.txt
  libhdf4.settings.cmake.in
Labels: Component - Build, Type - Improvement, Priority - 3. Low 🔽

#730 Fixed FetchContent usage for new CMake reqs.
  config/cmake/HDFLibMacros.cmake
  release_docs/RELEASE.txt
Labels: Component - Build, Type - Deprecation / Removal, Priority - 1. High 🔼

#732 Add publish files from branch workflow
  .github/workflows/cmake-ctest.yml
  .github/workflows/publish-branch.yml
  .github/workflows/publish-release.yml
  HDF4Examples/CMakePresets.json
  HDF4Examples/config/cmake/HDFExampleMacros.cmake
Labels: Component - Misc, Type - Task, Priority - 2. Medium ⏹
