Repository HDFGroup/hdf4, pull requests merged in 2025-01, with the labels that each got.

#796 Update CMake and libaec to follow hdf5 conventions
  .github/workflows/aocc-cmake.yml
  .github/workflows/cmake-analysis.yml
  .github/workflows/cmake-ctest.yml
  .github/workflows/cmake-script.yml
  .github/workflows/codespell.yml
  .github/workflows/main-cmake.yml
  .github/workflows/nvhpc-cmake.yml
  CMakeFilters.cmake
  CMakeLists.txt
  config/cmake-presets/hidden-presets.json
  config/cmake/HDFLibMacros.cmake
  config/cmake/SignPackageFiles.cmake
  config/cmake/grepTest.cmake
  config/cmake/jrunTest.cmake
  config/sanitizer/README.md
  config/sanitizer/sanitizers.cmake
  release_docs/INSTALL_CMake.txt
Labels: Component - Build, Component - Misc, Type - Improvement, Priority - 1. High 🔼

#799 Simplify the .gitattributes file
  .gitattributes
Labels: Component - Misc, Type - Improvement, Priority - 2. Medium ⏹

#800 Fix minor codespell issues
  .github/workflows/codespell.yml
  HDF4Examples/FORTRAN/GR/h4ex_GR_write_palette.f
  hdf/util/gif2mem.c
  mfhdf/src/mfsd.c
Labels: Component - Misc
